// RTDB gRPC API
// ------------------------------
// Version: 1.0.0
// Release date: 27.07.2026
// OrxaGrid, 2026
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: api/rtdb/rdss_dms_rtdb_api.proto

package rtdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rtdb_GetHealth_FullMethodName                 = "/rdss.dms.rtdb.v1.Rtdb/GetHealth"
	Rtdb_ReloadConfiguration_FullMethodName       = "/rdss.dms.rtdb.v1.Rtdb/ReloadConfiguration"
	Rtdb_IsExists_FullMethodName                  = "/rdss.dms.rtdb.v1.Rtdb/IsExists"
	Rtdb_GetAllItems_FullMethodName               = "/rdss.dms.rtdb.v1.Rtdb/GetAllItems"
	Rtdb_GetItems_FullMethodName                  = "/rdss.dms.rtdb.v1.Rtdb/GetItems"
	Rtdb_GetItemSources_FullMethodName            = "/rdss.dms.rtdb.v1.Rtdb/GetItemSources"
	Rtdb_AddItems_FullMethodName                  = "/rdss.dms.rtdb.v1.Rtdb/AddItems"
	Rtdb_RemoveItems_FullMethodName               = "/rdss.dms.rtdb.v1.Rtdb/RemoveItems"
	Rtdb_WriteData_FullMethodName                 = "/rdss.dms.rtdb.v1.Rtdb/WriteData"
	Rtdb_SupervisoryControl_FullMethodName        = "/rdss.dms.rtdb.v1.Rtdb/SupervisoryControl"
	Rtdb_SupervisoryControlObject_FullMethodName  = "/rdss.dms.rtdb.v1.Rtdb/SupervisoryControlObject"
	Rtdb_SetCurrentSource_FullMethodName          = "/rdss.dms.rtdb.v1.Rtdb/SetCurrentSource"
	Rtdb_RegisterSource_FullMethodName            = "/rdss.dms.rtdb.v1.Rtdb/RegisterSource"
	Rtdb_GetAvailableSources_FullMethodName       = "/rdss.dms.rtdb.v1.Rtdb/GetAvailableSources"
	Rtdb_SetManualEnteredData_FullMethodName      = "/rdss.dms.rtdb.v1.Rtdb/SetManualEnteredData"
	Rtdb_GetManualEnteredData_FullMethodName      = "/rdss.dms.rtdb.v1.Rtdb/GetManualEnteredData"
	Rtdb_SetQuality_FullMethodName                = "/rdss.dms.rtdb.v1.Rtdb/SetQuality"
	Rtdb_GetThresholds_FullMethodName             = "/rdss.dms.rtdb.v1.Rtdb/GetThresholds"
	Rtdb_AddThreshold_FullMethodName              = "/rdss.dms.rtdb.v1.Rtdb/AddThreshold"
	Rtdb_UpdateThreshold_FullMethodName           = "/rdss.dms.rtdb.v1.Rtdb/UpdateThreshold"
	Rtdb_DeleteThreshold_FullMethodName           = "/rdss.dms.rtdb.v1.Rtdb/DeleteThreshold"
	Rtdb_WriteDataStream_FullMethodName           = "/rdss.dms.rtdb.v1.Rtdb/WriteDataStream"
	Rtdb_Subscribe_FullMethodName                 = "/rdss.dms.rtdb.v1.Rtdb/Subscribe"
	Rtdb_ProtectionTerminalSetMode_FullMethodName = "/rdss.dms.rtdb.v1.Rtdb/ProtectionTerminalSetMode"
)

// RtdbClient is the client API for Rtdb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RtdbClient interface {
	// Health check - reports the server's build version, when it started, and how many
	// points it currently holds. Side-effect-free; intended as a lightweight liveness
	// probe for clients that previously had to stand one in with an unrelated RPC like
	// GetAvailableSources.
	GetHealth(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBHealthResponse, error)
	// Reload configuration from the database
	ReloadConfiguration(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Checking if item exists in RTDB
	IsExists(ctx context.Context, in *RTDBItemExistsRequest, opts ...grpc.CallOption) (*RTDBItemExistsResponse, error)
	// Retrieves information about all items created in the RTDB.
	GetAllItems(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error)
	// Retrieves information about items by a specified list of identifiers.
	// If the item is not created, its data will not be included in the response.
	GetItems(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error)
	// Retrieves the last data received from every source of each specified point, keyed by source
	// identifier. Unlike GetItems, a point identifier not found in the RTDB is omitted from the
	// response rather than created.
	GetItemSources(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemSourcesResponse, error)
	// Creates items in the RTDB with default data.
	// If the item has been created earlier, information about it will be included in the response.
	AddItems(ctx context.Context, in *RTDBAddItemsRequest, opts ...grpc.CallOption) (*RTDBKeysResponse, error)
	// Removes items and data from the RTDB.
	// If the item is associated with a source, the link with it is removed from the source.
	RemoveItems(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Performs writing data to the specified items.
	// If the item with the specified identifier is not found, the method will
	// create a item with the passed data.
	WriteData(ctx context.Context, in *RTDBWriteItemsRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Performs Supervisory Control for the specified tag.
	SupervisoryControl(ctx context.Context, in *RTDBSupervisoryControlRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error)
	// Performs Supervisory Control for the specified object mrid.
	SupervisoryControlObject(ctx context.Context, in *RTDBSupervisoryControlObjectRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error)
	// Set current source for selected point
	SetCurrentSource(ctx context.Context, in *RTDBSetCurrentSourceRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Register new source
	// A new data source is added for the selected points. If the point identifier is ALL, the new source is added
	// for all points. A dictionary entry for existing sources is also added.
	RegisterSource(ctx context.Context, in *RTDBRegisterSourceRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Gets a list of available sources
	GetAvailableSources(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBSourcesResponse, error)
	// Set manual entered data for the selected point
	SetManualEnteredData(ctx context.Context, in *RTDBSetManualEnteredDataRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Retrieves the last manually entered (MED) value for each specified point. A point not found in
	// the RTDB, or with no MED value recorded yet, is omitted from the response rather than created -
	// the same convention GetItemSources/GetThresholds already follow.
	GetManualEnteredData(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error)
	// Set quality descriptor for selected points
	SetQuality(ctx context.Context, in *RTDBSetQualityRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Retrieves the configured thresholds (upper/lower warning/alarm limits) for each specified point,
	// keyed by threshold type. A point with no configured thresholds, or not found in the RTDB, is
	// omitted from the response rather than created.
	GetThresholds(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBThresholdsResponse, error)
	// Adds a threshold of the given type for a point. Fails with ALREADY_EXISTS if a threshold of that
	// type is already configured for the point - use UpdateThreshold to change it instead.
	AddThreshold(ctx context.Context, in *RTDBThreshold, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Updates the value of an existing threshold. Fails with NOT_FOUND if no threshold of that type is
	// configured for the point.
	UpdateThreshold(ctx context.Context, in *RTDBThreshold, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Removes a threshold of the given type from a point. Fails with NOT_FOUND if no threshold of that
	// type is configured for the point.
	DeleteThreshold(ctx context.Context, in *RTDBDeleteThresholdRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error)
	// Creates a client-to-server data writing stream.
	// The method provides maximum data writing performance.
	// Data writing is performed without confirmation (no reverse flow from server to client).
	// The method creates missing items and performs writing.
	WriteDataStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RTDBWriteItemsRequest, RTDBEmptyResponse], error)
	// Creates a data subscription stream from the server to the client.
	// Upon opening the stream, the server sends the current data slice for the specified list of items,
	// subsequent data transmission occurs upon change and periodically according
	// to the specified subscription parameters.
	Subscribe(ctx context.Context, in *RTDBSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RTDBItemsResponse], error)
	// Sets a breaker's IEC 61850 Mod-style operating mode (On/Blocked/Test/
	// Off), controlling whether it accepts control commands and whether its
	// protection function drives real physical output.
	ProtectionTerminalSetMode(ctx context.Context, in *ProtectionTerminalSetModeRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error)
}

type rtdbClient struct {
	cc grpc.ClientConnInterface
}

func NewRtdbClient(cc grpc.ClientConnInterface) RtdbClient {
	return &rtdbClient{cc}
}

func (c *rtdbClient) GetHealth(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBHealthResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) ReloadConfiguration(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_ReloadConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) IsExists(ctx context.Context, in *RTDBItemExistsRequest, opts ...grpc.CallOption) (*RTDBItemExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBItemExistsResponse)
	err := c.cc.Invoke(ctx, Rtdb_IsExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetAllItems(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBItemsResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetAllItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetItems(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBItemsResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetItemSources(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBItemSourcesResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetItemSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) AddItems(ctx context.Context, in *RTDBAddItemsRequest, opts ...grpc.CallOption) (*RTDBKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBKeysResponse)
	err := c.cc.Invoke(ctx, Rtdb_AddItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) RemoveItems(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_RemoveItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) WriteData(ctx context.Context, in *RTDBWriteItemsRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_WriteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) SupervisoryControl(ctx context.Context, in *RTDBSupervisoryControlRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBSupervisoryControlResponse)
	err := c.cc.Invoke(ctx, Rtdb_SupervisoryControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) SupervisoryControlObject(ctx context.Context, in *RTDBSupervisoryControlObjectRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBSupervisoryControlResponse)
	err := c.cc.Invoke(ctx, Rtdb_SupervisoryControlObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) SetCurrentSource(ctx context.Context, in *RTDBSetCurrentSourceRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_SetCurrentSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) RegisterSource(ctx context.Context, in *RTDBRegisterSourceRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_RegisterSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetAvailableSources(ctx context.Context, in *RTDBEmptyRequest, opts ...grpc.CallOption) (*RTDBSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBSourcesResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetAvailableSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) SetManualEnteredData(ctx context.Context, in *RTDBSetManualEnteredDataRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_SetManualEnteredData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetManualEnteredData(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBItemsResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetManualEnteredData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) SetQuality(ctx context.Context, in *RTDBSetQualityRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_SetQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) GetThresholds(ctx context.Context, in *RTDBKeysRequest, opts ...grpc.CallOption) (*RTDBThresholdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBThresholdsResponse)
	err := c.cc.Invoke(ctx, Rtdb_GetThresholds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) AddThreshold(ctx context.Context, in *RTDBThreshold, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_AddThreshold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) UpdateThreshold(ctx context.Context, in *RTDBThreshold, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_UpdateThreshold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) DeleteThreshold(ctx context.Context, in *RTDBDeleteThresholdRequest, opts ...grpc.CallOption) (*RTDBEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBEmptyResponse)
	err := c.cc.Invoke(ctx, Rtdb_DeleteThreshold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtdbClient) WriteDataStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RTDBWriteItemsRequest, RTDBEmptyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rtdb_ServiceDesc.Streams[0], Rtdb_WriteDataStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RTDBWriteItemsRequest, RTDBEmptyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rtdb_WriteDataStreamClient = grpc.ClientStreamingClient[RTDBWriteItemsRequest, RTDBEmptyResponse]

func (c *rtdbClient) Subscribe(ctx context.Context, in *RTDBSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RTDBItemsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rtdb_ServiceDesc.Streams[1], Rtdb_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RTDBSubscribeRequest, RTDBItemsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rtdb_SubscribeClient = grpc.ServerStreamingClient[RTDBItemsResponse]

func (c *rtdbClient) ProtectionTerminalSetMode(ctx context.Context, in *ProtectionTerminalSetModeRequest, opts ...grpc.CallOption) (*RTDBSupervisoryControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTDBSupervisoryControlResponse)
	err := c.cc.Invoke(ctx, Rtdb_ProtectionTerminalSetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RtdbServer is the server API for Rtdb service.
// All implementations must embed UnimplementedRtdbServer
// for forward compatibility.
type RtdbServer interface {
	// Health check - reports the server's build version, when it started, and how many
	// points it currently holds. Side-effect-free; intended as a lightweight liveness
	// probe for clients that previously had to stand one in with an unrelated RPC like
	// GetAvailableSources.
	GetHealth(context.Context, *RTDBEmptyRequest) (*RTDBHealthResponse, error)
	// Reload configuration from the database
	ReloadConfiguration(context.Context, *RTDBEmptyRequest) (*RTDBEmptyResponse, error)
	// Checking if item exists in RTDB
	IsExists(context.Context, *RTDBItemExistsRequest) (*RTDBItemExistsResponse, error)
	// Retrieves information about all items created in the RTDB.
	GetAllItems(context.Context, *RTDBEmptyRequest) (*RTDBItemsResponse, error)
	// Retrieves information about items by a specified list of identifiers.
	// If the item is not created, its data will not be included in the response.
	GetItems(context.Context, *RTDBKeysRequest) (*RTDBItemsResponse, error)
	// Retrieves the last data received from every source of each specified point, keyed by source
	// identifier. Unlike GetItems, a point identifier not found in the RTDB is omitted from the
	// response rather than created.
	GetItemSources(context.Context, *RTDBKeysRequest) (*RTDBItemSourcesResponse, error)
	// Creates items in the RTDB with default data.
	// If the item has been created earlier, information about it will be included in the response.
	AddItems(context.Context, *RTDBAddItemsRequest) (*RTDBKeysResponse, error)
	// Removes items and data from the RTDB.
	// If the item is associated with a source, the link with it is removed from the source.
	RemoveItems(context.Context, *RTDBKeysRequest) (*RTDBEmptyResponse, error)
	// Performs writing data to the specified items.
	// If the item with the specified identifier is not found, the method will
	// create a item with the passed data.
	WriteData(context.Context, *RTDBWriteItemsRequest) (*RTDBEmptyResponse, error)
	// Performs Supervisory Control for the specified tag.
	SupervisoryControl(context.Context, *RTDBSupervisoryControlRequest) (*RTDBSupervisoryControlResponse, error)
	// Performs Supervisory Control for the specified object mrid.
	SupervisoryControlObject(context.Context, *RTDBSupervisoryControlObjectRequest) (*RTDBSupervisoryControlResponse, error)
	// Set current source for selected point
	SetCurrentSource(context.Context, *RTDBSetCurrentSourceRequest) (*RTDBEmptyResponse, error)
	// Register new source
	// A new data source is added for the selected points. If the point identifier is ALL, the new source is added
	// for all points. A dictionary entry for existing sources is also added.
	RegisterSource(context.Context, *RTDBRegisterSourceRequest) (*RTDBEmptyResponse, error)
	// Gets a list of available sources
	GetAvailableSources(context.Context, *RTDBEmptyRequest) (*RTDBSourcesResponse, error)
	// Set manual entered data for the selected point
	SetManualEnteredData(context.Context, *RTDBSetManualEnteredDataRequest) (*RTDBEmptyResponse, error)
	// Retrieves the last manually entered (MED) value for each specified point. A point not found in
	// the RTDB, or with no MED value recorded yet, is omitted from the response rather than created -
	// the same convention GetItemSources/GetThresholds already follow.
	GetManualEnteredData(context.Context, *RTDBKeysRequest) (*RTDBItemsResponse, error)
	// Set quality descriptor for selected points
	SetQuality(context.Context, *RTDBSetQualityRequest) (*RTDBEmptyResponse, error)
	// Retrieves the configured thresholds (upper/lower warning/alarm limits) for each specified point,
	// keyed by threshold type. A point with no configured thresholds, or not found in the RTDB, is
	// omitted from the response rather than created.
	GetThresholds(context.Context, *RTDBKeysRequest) (*RTDBThresholdsResponse, error)
	// Adds a threshold of the given type for a point. Fails with ALREADY_EXISTS if a threshold of that
	// type is already configured for the point - use UpdateThreshold to change it instead.
	AddThreshold(context.Context, *RTDBThreshold) (*RTDBEmptyResponse, error)
	// Updates the value of an existing threshold. Fails with NOT_FOUND if no threshold of that type is
	// configured for the point.
	UpdateThreshold(context.Context, *RTDBThreshold) (*RTDBEmptyResponse, error)
	// Removes a threshold of the given type from a point. Fails with NOT_FOUND if no threshold of that
	// type is configured for the point.
	DeleteThreshold(context.Context, *RTDBDeleteThresholdRequest) (*RTDBEmptyResponse, error)
	// Creates a client-to-server data writing stream.
	// The method provides maximum data writing performance.
	// Data writing is performed without confirmation (no reverse flow from server to client).
	// The method creates missing items and performs writing.
	WriteDataStream(grpc.ClientStreamingServer[RTDBWriteItemsRequest, RTDBEmptyResponse]) error
	// Creates a data subscription stream from the server to the client.
	// Upon opening the stream, the server sends the current data slice for the specified list of items,
	// subsequent data transmission occurs upon change and periodically according
	// to the specified subscription parameters.
	Subscribe(*RTDBSubscribeRequest, grpc.ServerStreamingServer[RTDBItemsResponse]) error
	// Sets a breaker's IEC 61850 Mod-style operating mode (On/Blocked/Test/
	// Off), controlling whether it accepts control commands and whether its
	// protection function drives real physical output.
	ProtectionTerminalSetMode(context.Context, *ProtectionTerminalSetModeRequest) (*RTDBSupervisoryControlResponse, error)
	mustEmbedUnimplementedRtdbServer()
}

// UnimplementedRtdbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRtdbServer struct{}

func (UnimplementedRtdbServer) GetHealth(context.Context, *RTDBEmptyRequest) (*RTDBHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedRtdbServer) ReloadConfiguration(context.Context, *RTDBEmptyRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfiguration not implemented")
}
func (UnimplementedRtdbServer) IsExists(context.Context, *RTDBItemExistsRequest) (*RTDBItemExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsExists not implemented")
}
func (UnimplementedRtdbServer) GetAllItems(context.Context, *RTDBEmptyRequest) (*RTDBItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItems not implemented")
}
func (UnimplementedRtdbServer) GetItems(context.Context, *RTDBKeysRequest) (*RTDBItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedRtdbServer) GetItemSources(context.Context, *RTDBKeysRequest) (*RTDBItemSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemSources not implemented")
}
func (UnimplementedRtdbServer) AddItems(context.Context, *RTDBAddItemsRequest) (*RTDBKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItems not implemented")
}
func (UnimplementedRtdbServer) RemoveItems(context.Context, *RTDBKeysRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveItems not implemented")
}
func (UnimplementedRtdbServer) WriteData(context.Context, *RTDBWriteItemsRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteData not implemented")
}
func (UnimplementedRtdbServer) SupervisoryControl(context.Context, *RTDBSupervisoryControlRequest) (*RTDBSupervisoryControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupervisoryControl not implemented")
}
func (UnimplementedRtdbServer) SupervisoryControlObject(context.Context, *RTDBSupervisoryControlObjectRequest) (*RTDBSupervisoryControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupervisoryControlObject not implemented")
}
func (UnimplementedRtdbServer) SetCurrentSource(context.Context, *RTDBSetCurrentSourceRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCurrentSource not implemented")
}
func (UnimplementedRtdbServer) RegisterSource(context.Context, *RTDBRegisterSourceRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSource not implemented")
}
func (UnimplementedRtdbServer) GetAvailableSources(context.Context, *RTDBEmptyRequest) (*RTDBSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableSources not implemented")
}
func (UnimplementedRtdbServer) SetManualEnteredData(context.Context, *RTDBSetManualEnteredDataRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetManualEnteredData not implemented")
}
func (UnimplementedRtdbServer) GetManualEnteredData(context.Context, *RTDBKeysRequest) (*RTDBItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManualEnteredData not implemented")
}
func (UnimplementedRtdbServer) SetQuality(context.Context, *RTDBSetQualityRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetQuality not implemented")
}
func (UnimplementedRtdbServer) GetThresholds(context.Context, *RTDBKeysRequest) (*RTDBThresholdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThresholds not implemented")
}
func (UnimplementedRtdbServer) AddThreshold(context.Context, *RTDBThreshold) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddThreshold not implemented")
}
func (UnimplementedRtdbServer) UpdateThreshold(context.Context, *RTDBThreshold) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateThreshold not implemented")
}
func (UnimplementedRtdbServer) DeleteThreshold(context.Context, *RTDBDeleteThresholdRequest) (*RTDBEmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteThreshold not implemented")
}
func (UnimplementedRtdbServer) WriteDataStream(grpc.ClientStreamingServer[RTDBWriteItemsRequest, RTDBEmptyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WriteDataStream not implemented")
}
func (UnimplementedRtdbServer) Subscribe(*RTDBSubscribeRequest, grpc.ServerStreamingServer[RTDBItemsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedRtdbServer) ProtectionTerminalSetMode(context.Context, *ProtectionTerminalSetModeRequest) (*RTDBSupervisoryControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProtectionTerminalSetMode not implemented")
}
func (UnimplementedRtdbServer) mustEmbedUnimplementedRtdbServer() {}
func (UnimplementedRtdbServer) testEmbeddedByValue()              {}

// UnsafeRtdbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RtdbServer will
// result in compilation errors.
type UnsafeRtdbServer interface {
	mustEmbedUnimplementedRtdbServer()
}

func RegisterRtdbServer(s grpc.ServiceRegistrar, srv RtdbServer) {
	// If the following call pancis, it indicates UnimplementedRtdbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rtdb_ServiceDesc, srv)
}

func _Rtdb_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetHealth(ctx, req.(*RTDBEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_ReloadConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).ReloadConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_ReloadConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).ReloadConfiguration(ctx, req.(*RTDBEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_IsExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBItemExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).IsExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_IsExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).IsExists(ctx, req.(*RTDBItemExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetAllItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetAllItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetAllItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetAllItems(ctx, req.(*RTDBEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetItems(ctx, req.(*RTDBKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetItemSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetItemSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetItemSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetItemSources(ctx, req.(*RTDBKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_AddItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBAddItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).AddItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_AddItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).AddItems(ctx, req.(*RTDBAddItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_RemoveItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).RemoveItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_RemoveItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).RemoveItems(ctx, req.(*RTDBKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_WriteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBWriteItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).WriteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_WriteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).WriteData(ctx, req.(*RTDBWriteItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_SupervisoryControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBSupervisoryControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).SupervisoryControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_SupervisoryControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).SupervisoryControl(ctx, req.(*RTDBSupervisoryControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_SupervisoryControlObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBSupervisoryControlObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).SupervisoryControlObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_SupervisoryControlObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).SupervisoryControlObject(ctx, req.(*RTDBSupervisoryControlObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_SetCurrentSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBSetCurrentSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).SetCurrentSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_SetCurrentSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).SetCurrentSource(ctx, req.(*RTDBSetCurrentSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_RegisterSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBRegisterSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).RegisterSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_RegisterSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).RegisterSource(ctx, req.(*RTDBRegisterSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetAvailableSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetAvailableSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetAvailableSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetAvailableSources(ctx, req.(*RTDBEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_SetManualEnteredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBSetManualEnteredDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).SetManualEnteredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_SetManualEnteredData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).SetManualEnteredData(ctx, req.(*RTDBSetManualEnteredDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetManualEnteredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetManualEnteredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetManualEnteredData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetManualEnteredData(ctx, req.(*RTDBKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_SetQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBSetQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).SetQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_SetQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).SetQuality(ctx, req.(*RTDBSetQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_GetThresholds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).GetThresholds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_GetThresholds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).GetThresholds(ctx, req.(*RTDBKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_AddThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBThreshold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).AddThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_AddThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).AddThreshold(ctx, req.(*RTDBThreshold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_UpdateThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBThreshold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).UpdateThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_UpdateThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).UpdateThreshold(ctx, req.(*RTDBThreshold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_DeleteThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTDBDeleteThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).DeleteThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_DeleteThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).DeleteThreshold(ctx, req.(*RTDBDeleteThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rtdb_WriteDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RtdbServer).WriteDataStream(&grpc.GenericServerStream[RTDBWriteItemsRequest, RTDBEmptyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rtdb_WriteDataStreamServer = grpc.ClientStreamingServer[RTDBWriteItemsRequest, RTDBEmptyResponse]

func _Rtdb_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RTDBSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RtdbServer).Subscribe(m, &grpc.GenericServerStream[RTDBSubscribeRequest, RTDBItemsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rtdb_SubscribeServer = grpc.ServerStreamingServer[RTDBItemsResponse]

func _Rtdb_ProtectionTerminalSetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectionTerminalSetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtdbServer).ProtectionTerminalSetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rtdb_ProtectionTerminalSetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtdbServer).ProtectionTerminalSetMode(ctx, req.(*ProtectionTerminalSetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rtdb_ServiceDesc is the grpc.ServiceDesc for Rtdb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rtdb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rdss.dms.rtdb.v1.Rtdb",
	HandlerType: (*RtdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Rtdb_GetHealth_Handler,
		},
		{
			MethodName: "ReloadConfiguration",
			Handler:    _Rtdb_ReloadConfiguration_Handler,
		},
		{
			MethodName: "IsExists",
			Handler:    _Rtdb_IsExists_Handler,
		},
		{
			MethodName: "GetAllItems",
			Handler:    _Rtdb_GetAllItems_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Rtdb_GetItems_Handler,
		},
		{
			MethodName: "GetItemSources",
			Handler:    _Rtdb_GetItemSources_Handler,
		},
		{
			MethodName: "AddItems",
			Handler:    _Rtdb_AddItems_Handler,
		},
		{
			MethodName: "RemoveItems",
			Handler:    _Rtdb_RemoveItems_Handler,
		},
		{
			MethodName: "WriteData",
			Handler:    _Rtdb_WriteData_Handler,
		},
		{
			MethodName: "SupervisoryControl",
			Handler:    _Rtdb_SupervisoryControl_Handler,
		},
		{
			MethodName: "SupervisoryControlObject",
			Handler:    _Rtdb_SupervisoryControlObject_Handler,
		},
		{
			MethodName: "SetCurrentSource",
			Handler:    _Rtdb_SetCurrentSource_Handler,
		},
		{
			MethodName: "RegisterSource",
			Handler:    _Rtdb_RegisterSource_Handler,
		},
		{
			MethodName: "GetAvailableSources",
			Handler:    _Rtdb_GetAvailableSources_Handler,
		},
		{
			MethodName: "SetManualEnteredData",
			Handler:    _Rtdb_SetManualEnteredData_Handler,
		},
		{
			MethodName: "GetManualEnteredData",
			Handler:    _Rtdb_GetManualEnteredData_Handler,
		},
		{
			MethodName: "SetQuality",
			Handler:    _Rtdb_SetQuality_Handler,
		},
		{
			MethodName: "GetThresholds",
			Handler:    _Rtdb_GetThresholds_Handler,
		},
		{
			MethodName: "AddThreshold",
			Handler:    _Rtdb_AddThreshold_Handler,
		},
		{
			MethodName: "UpdateThreshold",
			Handler:    _Rtdb_UpdateThreshold_Handler,
		},
		{
			MethodName: "DeleteThreshold",
			Handler:    _Rtdb_DeleteThreshold_Handler,
		},
		{
			MethodName: "ProtectionTerminalSetMode",
			Handler:    _Rtdb_ProtectionTerminalSetMode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteDataStream",
			Handler:       _Rtdb_WriteDataStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Rtdb_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/rtdb/rdss_dms_rtdb_api.proto",
}
