// RTDB gRPC API
// ------------------------------
// Version: 1.0.0
// Release date: 27.07.2026
// OrxaGrid, 2026
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: api/rtdb/rdss_dms_rtdb_api.proto

package rtdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RTDBSupervisoryControlResult int32

const (
	RTDBSupervisoryControlResult_OK                        RTDBSupervisoryControlResult = 0
	RTDBSupervisoryControlResult_ERROR_TIMEOUT             RTDBSupervisoryControlResult = 1
	RTDBSupervisoryControlResult_ERROR_BLOCKED             RTDBSupervisoryControlResult = 2
	RTDBSupervisoryControlResult_ERROR_UNKNOW              RTDBSupervisoryControlResult = 3
	RTDBSupervisoryControlResult_ERROR_NOT_SUPPORTED       RTDBSupervisoryControlResult = 4
	RTDBSupervisoryControlResult_ERROR_OBJECT_IS_NOT_FOUND RTDBSupervisoryControlResult = 5
	RTDBSupervisoryControlResult_ERROR_ITEM_IS_NOT_FOUND   RTDBSupervisoryControlResult = 6
	RTDBSupervisoryControlResult_ERROR_NOT_SELECTED        RTDBSupervisoryControlResult = 7
)

// Enum value maps for RTDBSupervisoryControlResult.
var (
	RTDBSupervisoryControlResult_name = map[int32]string{
		0: "OK",
		1: "ERROR_TIMEOUT",
		2: "ERROR_BLOCKED",
		3: "ERROR_UNKNOW",
		4: "ERROR_NOT_SUPPORTED",
		5: "ERROR_OBJECT_IS_NOT_FOUND",
		6: "ERROR_ITEM_IS_NOT_FOUND",
		7: "ERROR_NOT_SELECTED",
	}
	RTDBSupervisoryControlResult_value = map[string]int32{
		"OK":                        0,
		"ERROR_TIMEOUT":             1,
		"ERROR_BLOCKED":             2,
		"ERROR_UNKNOW":              3,
		"ERROR_NOT_SUPPORTED":       4,
		"ERROR_OBJECT_IS_NOT_FOUND": 5,
		"ERROR_ITEM_IS_NOT_FOUND":   6,
		"ERROR_NOT_SELECTED":        7,
	}
)

func (x RTDBSupervisoryControlResult) Enum() *RTDBSupervisoryControlResult {
	p := new(RTDBSupervisoryControlResult)
	*p = x
	return p
}

func (x RTDBSupervisoryControlResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTDBSupervisoryControlResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[0].Descriptor()
}

func (RTDBSupervisoryControlResult) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[0]
}

func (x RTDBSupervisoryControlResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTDBSupervisoryControlResult.Descriptor instead.
func (RTDBSupervisoryControlResult) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{0}
}

// Kinds of threshold that can be configured on a point, mirroring objects.threshold_type - ids match
// that table's rows exactly (1-4), not independently assigned.
type RTDBThresholdType int32

const (
	RTDBThresholdType_THRESHOLD_TYPE_NOT_SET RTDBThresholdType = 0
	RTDBThresholdType_UPPER_WARNING_LIMIT    RTDBThresholdType = 1
	RTDBThresholdType_LOWER_WARNING_LIMIT    RTDBThresholdType = 2
	RTDBThresholdType_UPPER_ALARM_LIMIT      RTDBThresholdType = 3
	RTDBThresholdType_LOWER_ALARM_LIMIT      RTDBThresholdType = 4
)

// Enum value maps for RTDBThresholdType.
var (
	RTDBThresholdType_name = map[int32]string{
		0: "THRESHOLD_TYPE_NOT_SET",
		1: "UPPER_WARNING_LIMIT",
		2: "LOWER_WARNING_LIMIT",
		3: "UPPER_ALARM_LIMIT",
		4: "LOWER_ALARM_LIMIT",
	}
	RTDBThresholdType_value = map[string]int32{
		"THRESHOLD_TYPE_NOT_SET": 0,
		"UPPER_WARNING_LIMIT":    1,
		"LOWER_WARNING_LIMIT":    2,
		"UPPER_ALARM_LIMIT":      3,
		"LOWER_ALARM_LIMIT":      4,
	}
)

func (x RTDBThresholdType) Enum() *RTDBThresholdType {
	p := new(RTDBThresholdType)
	*p = x
	return p
}

func (x RTDBThresholdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTDBThresholdType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[1].Descriptor()
}

func (RTDBThresholdType) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[1]
}

func (x RTDBThresholdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTDBThresholdType.Descriptor instead.
func (RTDBThresholdType) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{1}
}

// Type of value change control
type RTDBSubscribeDataControl int32

const (
	// Value change control is disabled
	// All data records to the client are sent
	RTDBSubscribeDataControl_OFF RTDBSubscribeDataControl = 0
	// Absolute value change control
	// Data is sent if the change in data in absolute value
	// relative to the last transmitted value is greater
	// by the amount specified in the subscription options (delta)
	RTDBSubscribeDataControl_VALUE RTDBSubscribeDataControl = 1
	// Percentage change control
	// Data is sent if the change in data in percentage
	// relative to the last transmitted value
	// is greater by the amount specified in the subscription options (delta)
	RTDBSubscribeDataControl_PERCENT RTDBSubscribeDataControl = 2
)

// Enum value maps for RTDBSubscribeDataControl.
var (
	RTDBSubscribeDataControl_name = map[int32]string{
		0: "OFF",
		1: "VALUE",
		2: "PERCENT",
	}
	RTDBSubscribeDataControl_value = map[string]int32{
		"OFF":     0,
		"VALUE":   1,
		"PERCENT": 2,
	}
)

func (x RTDBSubscribeDataControl) Enum() *RTDBSubscribeDataControl {
	p := new(RTDBSubscribeDataControl)
	*p = x
	return p
}

func (x RTDBSubscribeDataControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTDBSubscribeDataControl) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[2].Descriptor()
}

func (RTDBSubscribeDataControl) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[2]
}

func (x RTDBSubscribeDataControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTDBSubscribeDataControl.Descriptor instead.
func (RTDBSubscribeDataControl) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{2}
}

// Known sources
type RTDBKnownSources int32

const (
	RTDBKnownSources_SOURCE_NOT_SET      RTDBKnownSources = 0
	RTDBKnownSources_MANUAL_ENTERED_DATA RTDBKnownSources = 1
	RTDBKnownSources_CALCULATOR          RTDBKnownSources = 2
)

// Enum value maps for RTDBKnownSources.
var (
	RTDBKnownSources_name = map[int32]string{
		0: "SOURCE_NOT_SET",
		1: "MANUAL_ENTERED_DATA",
		2: "CALCULATOR",
	}
	RTDBKnownSources_value = map[string]int32{
		"SOURCE_NOT_SET":      0,
		"MANUAL_ENTERED_DATA": 1,
		"CALCULATOR":          2,
	}
)

func (x RTDBKnownSources) Enum() *RTDBKnownSources {
	p := new(RTDBKnownSources)
	*p = x
	return p
}

func (x RTDBKnownSources) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTDBKnownSources) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[3].Descriptor()
}

func (RTDBKnownSources) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[3]
}

func (x RTDBKnownSources) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTDBKnownSources.Descriptor instead.
func (RTDBKnownSources) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{3}
}

// Data types
type RTDBItemType int32

const (
	RTDBItemType_TYPE_NOT_SET     RTDBItemType = 0
	RTDBItemType_DIGITAL_1BIT     RTDBItemType = 1
	RTDBItemType_DIGITAL_2BIT     RTDBItemType = 2
	RTDBItemType_ANALOG           RTDBItemType = 3
	RTDBItemType_PROTECTION_EVENT RTDBItemType = 4
	RTDBItemType_INTEGER          RTDBItemType = 5
)

// Enum value maps for RTDBItemType.
var (
	RTDBItemType_name = map[int32]string{
		0: "TYPE_NOT_SET",
		1: "DIGITAL_1BIT",
		2: "DIGITAL_2BIT",
		3: "ANALOG",
		4: "PROTECTION_EVENT",
		5: "INTEGER",
	}
	RTDBItemType_value = map[string]int32{
		"TYPE_NOT_SET":     0,
		"DIGITAL_1BIT":     1,
		"DIGITAL_2BIT":     2,
		"ANALOG":           3,
		"PROTECTION_EVENT": 4,
		"INTEGER":          5,
	}
)

func (x RTDBItemType) Enum() *RTDBItemType {
	p := new(RTDBItemType)
	*p = x
	return p
}

func (x RTDBItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTDBItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[4].Descriptor()
}

func (RTDBItemType) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[4]
}

func (x RTDBItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTDBItemType.Descriptor instead.
func (RTDBItemType) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{4}
}

// ProtectionTerminalMode mirrors IEC 61850 Edition 1's Mod/Beh enumeration.
// TEST_BLOCKED (4) is deliberately not modelled by this simulator, so
// values skip from TEST (3) straight to OFF (5).
type ProtectionTerminalMode int32

const (
	ProtectionTerminalMode_MODE_UNKNOWN ProtectionTerminalMode = 0
	ProtectionTerminalMode_MODE_ON      ProtectionTerminalMode = 1
	ProtectionTerminalMode_MODE_BLOCKED ProtectionTerminalMode = 2
	ProtectionTerminalMode_MODE_TEST    ProtectionTerminalMode = 3
	ProtectionTerminalMode_MODE_OFF     ProtectionTerminalMode = 5
)

// Enum value maps for ProtectionTerminalMode.
var (
	ProtectionTerminalMode_name = map[int32]string{
		0: "MODE_UNKNOWN",
		1: "MODE_ON",
		2: "MODE_BLOCKED",
		3: "MODE_TEST",
		5: "MODE_OFF",
	}
	ProtectionTerminalMode_value = map[string]int32{
		"MODE_UNKNOWN": 0,
		"MODE_ON":      1,
		"MODE_BLOCKED": 2,
		"MODE_TEST":    3,
		"MODE_OFF":     5,
	}
)

func (x ProtectionTerminalMode) Enum() *ProtectionTerminalMode {
	p := new(ProtectionTerminalMode)
	*p = x
	return p
}

func (x ProtectionTerminalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtectionTerminalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[5].Descriptor()
}

func (ProtectionTerminalMode) Type() protoreflect.EnumType {
	return &file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes[5]
}

func (x ProtectionTerminalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtectionTerminalMode.Descriptor instead.
func (ProtectionTerminalMode) EnumDescriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{5}
}

// UUID representation
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Request without data (empty).
// Used when no data transmission is required.
type RTDBEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBEmptyRequest) Reset() {
	*x = RTDBEmptyRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBEmptyRequest) ProtoMessage() {}

func (x *RTDBEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBEmptyRequest.ProtoReflect.Descriptor instead.
func (*RTDBEmptyRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{1}
}

// Response without data (empty).
// Used when no data transmission is required.
type RTDBEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBEmptyResponse) Reset() {
	*x = RTDBEmptyResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBEmptyResponse) ProtoMessage() {}

func (x *RTDBEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBEmptyResponse.ProtoReflect.Descriptor instead.
func (*RTDBEmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{2}
}

// Response to a GetHealth request.
type RTDBHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build version string (git describe --tags --always plus build timestamp).
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// When this server process started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Number of points (items) currently held in the RTDB.
	PointsCount   int64 `protobuf:"varint,3,opt,name=points_count,json=pointsCount,proto3" json:"points_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBHealthResponse) Reset() {
	*x = RTDBHealthResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBHealthResponse) ProtoMessage() {}

func (x *RTDBHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBHealthResponse.ProtoReflect.Descriptor instead.
func (*RTDBHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{3}
}

func (x *RTDBHealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RTDBHealthResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RTDBHealthResponse) GetPointsCount() int64 {
	if x != nil {
		return x.PointsCount
	}
	return 0
}

// RTDB data value
type RTDBDataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the value
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Timestamp from FEP
	TimestampFep *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp_fep,json=timestampFep,proto3" json:"timestamp_fep,omitempty"`
	// Value
	Value float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	// Quality status
	Quality       uint32 `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBDataValue) Reset() {
	*x = RTDBDataValue{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBDataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBDataValue) ProtoMessage() {}

func (x *RTDBDataValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBDataValue.ProtoReflect.Descriptor instead.
func (*RTDBDataValue) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{4}
}

func (x *RTDBDataValue) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RTDBDataValue) GetTimestampFep() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampFep
	}
	return nil
}

func (x *RTDBDataValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RTDBDataValue) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

// RTDB item datapoint
type RTDBItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Timestamp of the last data update.
	UpdateAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	// Data
	Data *RTDBDataValue `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Type
	Type RTDBItemType `protobuf:"varint,4,opt,name=type,proto3,enum=rdss.dms.rtdb.v1.RTDBItemType" json:"type,omitempty"`
	// Current source. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source        uint64 `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItem) Reset() {
	*x = RTDBItem{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItem) ProtoMessage() {}

func (x *RTDBItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItem.ProtoReflect.Descriptor instead.
func (*RTDBItem) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{5}
}

func (x *RTDBItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBItem) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *RTDBItem) GetData() *RTDBDataValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RTDBItem) GetType() RTDBItemType {
	if x != nil {
		return x.Type
	}
	return RTDBItemType_TYPE_NOT_SET
}

func (x *RTDBItem) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

type RTDBSupervisoryControlItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Data
	Data *RTDBDataValue `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Current source. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source uint64 `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// Select flag
	Select bool `protobuf:"varint,4,opt,name=select,proto3" json:"select,omitempty"`
	// Execute flag
	Execute bool `protobuf:"varint,5,opt,name=execute,proto3" json:"execute,omitempty"`
	// Test flag
	Test          bool `protobuf:"varint,6,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSupervisoryControlItem) Reset() {
	*x = RTDBSupervisoryControlItem{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSupervisoryControlItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSupervisoryControlItem) ProtoMessage() {}

func (x *RTDBSupervisoryControlItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSupervisoryControlItem.ProtoReflect.Descriptor instead.
func (*RTDBSupervisoryControlItem) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{6}
}

func (x *RTDBSupervisoryControlItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBSupervisoryControlItem) GetData() *RTDBDataValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RTDBSupervisoryControlItem) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBSupervisoryControlItem) GetSelect() bool {
	if x != nil {
		return x.Select
	}
	return false
}

func (x *RTDBSupervisoryControlItem) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

func (x *RTDBSupervisoryControlItem) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

type RTDBSupervisoryControlObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier.
	Mrid *UUID `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	// Data
	Data *RTDBDataValue `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Current source. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source uint64 `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// Select flag
	Select bool `protobuf:"varint,4,opt,name=select,proto3" json:"select,omitempty"`
	// Execute flag
	Execute bool `protobuf:"varint,5,opt,name=execute,proto3" json:"execute,omitempty"`
	// Test flag
	Test          bool `protobuf:"varint,6,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSupervisoryControlObject) Reset() {
	*x = RTDBSupervisoryControlObject{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSupervisoryControlObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSupervisoryControlObject) ProtoMessage() {}

func (x *RTDBSupervisoryControlObject) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSupervisoryControlObject.ProtoReflect.Descriptor instead.
func (*RTDBSupervisoryControlObject) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{7}
}

func (x *RTDBSupervisoryControlObject) GetMrid() *UUID {
	if x != nil {
		return x.Mrid
	}
	return nil
}

func (x *RTDBSupervisoryControlObject) GetData() *RTDBDataValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RTDBSupervisoryControlObject) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBSupervisoryControlObject) GetSelect() bool {
	if x != nil {
		return x.Select
	}
	return false
}

func (x *RTDBSupervisoryControlObject) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

func (x *RTDBSupervisoryControlObject) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

// Request to add items
type RTDBKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of item identifiers.
	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBKeysRequest) Reset() {
	*x = RTDBKeysRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBKeysRequest) ProtoMessage() {}

func (x *RTDBKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBKeysRequest.ProtoReflect.Descriptor instead.
func (*RTDBKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{8}
}

func (x *RTDBKeysRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RTDBKeysRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Request item
type RTDBItemExistsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Item identifier (tag)
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItemExistsRequest) Reset() {
	*x = RTDBItemExistsRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItemExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItemExistsRequest) ProtoMessage() {}

func (x *RTDBItemExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItemExistsRequest.ProtoReflect.Descriptor instead.
func (*RTDBItemExistsRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{9}
}

func (x *RTDBItemExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Request item
type RTDBItemExistsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flag
	Exists        bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItemExistsResponse) Reset() {
	*x = RTDBItemExistsResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItemExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItemExistsResponse) ProtoMessage() {}

func (x *RTDBItemExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItemExistsResponse.ProtoReflect.Descriptor instead.
func (*RTDBItemExistsResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{10}
}

func (x *RTDBItemExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Request to create items
type RTDBAddItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of item identifiers.
	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Client text identifier for logging and debugging
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Current source to set for newly created items. Reserved identifiers: 1 = manually entered data,
	// 2 = calculator module. Cells that already exist are left untouched.
	Source uint64 `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	// Datatype
	Type          RTDBItemType `protobuf:"varint,4,opt,name=type,proto3,enum=rdss.dms.rtdb.v1.RTDBItemType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBAddItemsRequest) Reset() {
	*x = RTDBAddItemsRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBAddItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBAddItemsRequest) ProtoMessage() {}

func (x *RTDBAddItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBAddItemsRequest.ProtoReflect.Descriptor instead.
func (*RTDBAddItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{11}
}

func (x *RTDBAddItemsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RTDBAddItemsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RTDBAddItemsRequest) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBAddItemsRequest) GetType() RTDBItemType {
	if x != nil {
		return x.Type
	}
	return RTDBItemType_TYPE_NOT_SET
}

// Request to add items
type RTDBKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of item identifiers.
	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBKeysResponse) Reset() {
	*x = RTDBKeysResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBKeysResponse) ProtoMessage() {}

func (x *RTDBKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBKeysResponse.ProtoReflect.Descriptor instead.
func (*RTDBKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{12}
}

func (x *RTDBKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Response with information about items
type RTDBItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about items.
	Items         []*RTDBItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItemsResponse) Reset() {
	*x = RTDBItemsResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItemsResponse) ProtoMessage() {}

func (x *RTDBItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItemsResponse.ProtoReflect.Descriptor instead.
func (*RTDBItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{13}
}

func (x *RTDBItemsResponse) GetItems() []*RTDBItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Last data received from a single source for a point
type RTDBSourceData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source identifier. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source uint64 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	// Last data received from this source
	Data          *RTDBDataValue `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSourceData) Reset() {
	*x = RTDBSourceData{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSourceData) ProtoMessage() {}

func (x *RTDBSourceData) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSourceData.ProtoReflect.Descriptor instead.
func (*RTDBSourceData) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{14}
}

func (x *RTDBSourceData) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBSourceData) GetData() *RTDBDataValue {
	if x != nil {
		return x.Data
	}
	return nil
}

// Last data received from every source that has ever written to a point
type RTDBItemSources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Last data received from each source, keyed by source identifier
	Sources       []*RTDBSourceData `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItemSources) Reset() {
	*x = RTDBItemSources{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItemSources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItemSources) ProtoMessage() {}

func (x *RTDBItemSources) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItemSources.ProtoReflect.Descriptor instead.
func (*RTDBItemSources) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{15}
}

func (x *RTDBItemSources) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBItemSources) GetSources() []*RTDBSourceData {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Response with per-point source data
type RTDBItemSourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Points found in the RTDB; a requested key not found is omitted, not created.
	Items         []*RTDBItemSources `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBItemSourcesResponse) Reset() {
	*x = RTDBItemSourcesResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBItemSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBItemSourcesResponse) ProtoMessage() {}

func (x *RTDBItemSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBItemSourcesResponse.ProtoReflect.Descriptor instead.
func (*RTDBItemSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{16}
}

func (x *RTDBItemSourcesResponse) GetItems() []*RTDBItemSources {
	if x != nil {
		return x.Items
	}
	return nil
}

type RTDBWriteItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about items.
	Items []*RTDBItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBWriteItemsRequest) Reset() {
	*x = RTDBWriteItemsRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBWriteItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBWriteItemsRequest) ProtoMessage() {}

func (x *RTDBWriteItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBWriteItemsRequest.ProtoReflect.Descriptor instead.
func (*RTDBWriteItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{17}
}

func (x *RTDBWriteItemsRequest) GetItems() []*RTDBItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RTDBWriteItemsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RTDBSupervisoryControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about item
	Item *RTDBSupervisoryControlItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSupervisoryControlRequest) Reset() {
	*x = RTDBSupervisoryControlRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSupervisoryControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSupervisoryControlRequest) ProtoMessage() {}

func (x *RTDBSupervisoryControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSupervisoryControlRequest.ProtoReflect.Descriptor instead.
func (*RTDBSupervisoryControlRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{18}
}

func (x *RTDBSupervisoryControlRequest) GetItem() *RTDBSupervisoryControlItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *RTDBSupervisoryControlRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RTDBSupervisoryControlObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about object
	Object *RTDBSupervisoryControlObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSupervisoryControlObjectRequest) Reset() {
	*x = RTDBSupervisoryControlObjectRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSupervisoryControlObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSupervisoryControlObjectRequest) ProtoMessage() {}

func (x *RTDBSupervisoryControlObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSupervisoryControlObjectRequest.ProtoReflect.Descriptor instead.
func (*RTDBSupervisoryControlObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{19}
}

func (x *RTDBSupervisoryControlObjectRequest) GetObject() *RTDBSupervisoryControlObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *RTDBSupervisoryControlObjectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RTDBSupervisoryControlResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Result        RTDBSupervisoryControlResult `protobuf:"varint,1,opt,name=result,proto3,enum=rdss.dms.rtdb.v1.RTDBSupervisoryControlResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSupervisoryControlResponse) Reset() {
	*x = RTDBSupervisoryControlResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSupervisoryControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSupervisoryControlResponse) ProtoMessage() {}

func (x *RTDBSupervisoryControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSupervisoryControlResponse.ProtoReflect.Descriptor instead.
func (*RTDBSupervisoryControlResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{20}
}

func (x *RTDBSupervisoryControlResponse) GetResult() RTDBSupervisoryControlResult {
	if x != nil {
		return x.Result
	}
	return RTDBSupervisoryControlResult_OK
}

type RTDBSetManualEnteredDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// New manual entered data value
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSetManualEnteredDataRequest) Reset() {
	*x = RTDBSetManualEnteredDataRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSetManualEnteredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSetManualEnteredDataRequest) ProtoMessage() {}

func (x *RTDBSetManualEnteredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSetManualEnteredDataRequest.ProtoReflect.Descriptor instead.
func (*RTDBSetManualEnteredDataRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{21}
}

func (x *RTDBSetManualEnteredDataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBSetManualEnteredDataRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RTDBSetQualityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of item identifiers.
	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Quality status
	Quality       uint32 `protobuf:"varint,2,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSetQualityRequest) Reset() {
	*x = RTDBSetQualityRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSetQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSetQualityRequest) ProtoMessage() {}

func (x *RTDBSetQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSetQualityRequest.ProtoReflect.Descriptor instead.
func (*RTDBSetQualityRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{22}
}

func (x *RTDBSetQualityRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RTDBSetQualityRequest) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

// A single threshold configured (or to be configured) for a point. A point has at most one value per
// RTDBThresholdType.
type RTDBThreshold struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Which kind of threshold this is
	Type RTDBThresholdType `protobuf:"varint,2,opt,name=type,proto3,enum=rdss.dms.rtdb.v1.RTDBThresholdType" json:"type,omitempty"`
	// Threshold value
	Value         float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBThreshold) Reset() {
	*x = RTDBThreshold{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBThreshold) ProtoMessage() {}

func (x *RTDBThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBThreshold.ProtoReflect.Descriptor instead.
func (*RTDBThreshold) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{23}
}

func (x *RTDBThreshold) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBThreshold) GetType() RTDBThresholdType {
	if x != nil {
		return x.Type
	}
	return RTDBThresholdType_THRESHOLD_TYPE_NOT_SET
}

func (x *RTDBThreshold) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RTDBDeleteThresholdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Which kind of threshold to remove
	Type          RTDBThresholdType `protobuf:"varint,2,opt,name=type,proto3,enum=rdss.dms.rtdb.v1.RTDBThresholdType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBDeleteThresholdRequest) Reset() {
	*x = RTDBDeleteThresholdRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBDeleteThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBDeleteThresholdRequest) ProtoMessage() {}

func (x *RTDBDeleteThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBDeleteThresholdRequest.ProtoReflect.Descriptor instead.
func (*RTDBDeleteThresholdRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{24}
}

func (x *RTDBDeleteThresholdRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBDeleteThresholdRequest) GetType() RTDBThresholdType {
	if x != nil {
		return x.Type
	}
	return RTDBThresholdType_THRESHOLD_TYPE_NOT_SET
}

// One threshold value scoped to its type, as returned by GetThresholds (RTDBThreshold without the
// repeated key, since it's already scoped by the enclosing RTDBPointThresholds)
type RTDBThresholdValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RTDBThresholdType      `protobuf:"varint,1,opt,name=type,proto3,enum=rdss.dms.rtdb.v1.RTDBThresholdType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBThresholdValue) Reset() {
	*x = RTDBThresholdValue{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBThresholdValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBThresholdValue) ProtoMessage() {}

func (x *RTDBThresholdValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBThresholdValue.ProtoReflect.Descriptor instead.
func (*RTDBThresholdValue) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{25}
}

func (x *RTDBThresholdValue) GetType() RTDBThresholdType {
	if x != nil {
		return x.Type
	}
	return RTDBThresholdType_THRESHOLD_TYPE_NOT_SET
}

func (x *RTDBThresholdValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Every threshold configured for a single point
type RTDBPointThresholds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Configured thresholds, keyed by type
	Thresholds    []*RTDBThresholdValue `protobuf:"bytes,2,rep,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBPointThresholds) Reset() {
	*x = RTDBPointThresholds{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBPointThresholds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBPointThresholds) ProtoMessage() {}

func (x *RTDBPointThresholds) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBPointThresholds.ProtoReflect.Descriptor instead.
func (*RTDBPointThresholds) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{26}
}

func (x *RTDBPointThresholds) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBPointThresholds) GetThresholds() []*RTDBThresholdValue {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

// Response with per-point threshold data
type RTDBThresholdsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Points with at least one configured threshold; a requested key with none, or not found in the
	// RTDB, is omitted rather than created.
	Items         []*RTDBPointThresholds `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBThresholdsResponse) Reset() {
	*x = RTDBThresholdsResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBThresholdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBThresholdsResponse) ProtoMessage() {}

func (x *RTDBThresholdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBThresholdsResponse.ProtoReflect.Descriptor instead.
func (*RTDBThresholdsResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{27}
}

func (x *RTDBThresholdsResponse) GetItems() []*RTDBPointThresholds {
	if x != nil {
		return x.Items
	}
	return nil
}

type RTDBSetCurrentSourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Source to make current. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source        uint64 `protobuf:"varint,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSetCurrentSourceRequest) Reset() {
	*x = RTDBSetCurrentSourceRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSetCurrentSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSetCurrentSourceRequest) ProtoMessage() {}

func (x *RTDBSetCurrentSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSetCurrentSourceRequest.ProtoReflect.Descriptor instead.
func (*RTDBSetCurrentSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{28}
}

func (x *RTDBSetCurrentSourceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBSetCurrentSourceRequest) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

type RTDBRegisterSourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source to make current. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source uint64 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	// Source name for logging
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Point identifier. The reserved key "ALL", used alone, set new source for every item currently in the RTDB.
	Key           []string `protobuf:"bytes,3,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBRegisterSourceRequest) Reset() {
	*x = RTDBRegisterSourceRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBRegisterSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBRegisterSourceRequest) ProtoMessage() {}

func (x *RTDBRegisterSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBRegisterSourceRequest.ProtoReflect.Descriptor instead.
func (*RTDBRegisterSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{29}
}

func (x *RTDBRegisterSourceRequest) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBRegisterSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RTDBRegisterSourceRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

type RTDBSourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source identifier. Reserved identifiers: 1 = manually entered data, 2 = calculator module.
	Source uint64 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	// Source name for logging
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSourceInfo) Reset() {
	*x = RTDBSourceInfo{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSourceInfo) ProtoMessage() {}

func (x *RTDBSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSourceInfo.ProtoReflect.Descriptor instead.
func (*RTDBSourceInfo) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{30}
}

func (x *RTDBSourceInfo) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RTDBSourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RTDBSourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of currently registered sources.
	Sources       []*RTDBSourceInfo `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSourcesResponse) Reset() {
	*x = RTDBSourcesResponse{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSourcesResponse) ProtoMessage() {}

func (x *RTDBSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSourcesResponse.ProtoReflect.Descriptor instead.
func (*RTDBSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{31}
}

func (x *RTDBSourcesResponse) GetSources() []*RTDBSourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Request to open a data subscription channel
type RTDBSubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription options for receiving data from items.
	// Pass a single option with key "ALL" to subscribe to every item currently in the RTDB.
	ItemOptions []*RTDBSubscribeItemOptions `protobuf:"bytes,1,rep,name=item_options,json=itemOptions,proto3" json:"item_options,omitempty"`
	// Slice sending period in seconds.
	// If set to 0, periodic slice sending is not performed
	SendPeriod int32 `protobuf:"varint,2,opt,name=send_period,json=sendPeriod,proto3" json:"send_period,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSubscribeRequest) Reset() {
	*x = RTDBSubscribeRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSubscribeRequest) ProtoMessage() {}

func (x *RTDBSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSubscribeRequest.ProtoReflect.Descriptor instead.
func (*RTDBSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{32}
}

func (x *RTDBSubscribeRequest) GetItemOptions() []*RTDBSubscribeItemOptions {
	if x != nil {
		return x.ItemOptions
	}
	return nil
}

func (x *RTDBSubscribeRequest) GetSendPeriod() int32 {
	if x != nil {
		return x.SendPeriod
	}
	return 0
}

func (x *RTDBSubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Subscription options for receiving data from items in the RTDB
type RTDBSubscribeItemOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier. The reserved key "ALL", used alone, subscribes to every item currently in the RTDB.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Type of value change control
	ControlType RTDBSubscribeDataControl `protobuf:"varint,2,opt,name=control_type,json=controlType,proto3,enum=rdss.dms.rtdb.v1.RTDBSubscribeDataControl" json:"control_type,omitempty"`
	// Value control amount
	Delta         float64 `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTDBSubscribeItemOptions) Reset() {
	*x = RTDBSubscribeItemOptions{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTDBSubscribeItemOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTDBSubscribeItemOptions) ProtoMessage() {}

func (x *RTDBSubscribeItemOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTDBSubscribeItemOptions.ProtoReflect.Descriptor instead.
func (*RTDBSubscribeItemOptions) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{33}
}

func (x *RTDBSubscribeItemOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RTDBSubscribeItemOptions) GetControlType() RTDBSubscribeDataControl {
	if x != nil {
		return x.ControlType
	}
	return RTDBSubscribeDataControl_OFF
}

func (x *RTDBSubscribeItemOptions) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ProtectionTerminalSetModeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier, "<breaker-name>.mode"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The mode to set the breaker to
	Mode ProtectionTerminalMode `protobuf:"varint,2,opt,name=mode,proto3,enum=rdss.dms.rtdb.v1.ProtectionTerminalMode" json:"mode,omitempty"`
	// Why the mode is being changed, for logging
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectionTerminalSetModeRequest) Reset() {
	*x = ProtectionTerminalSetModeRequest{}
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectionTerminalSetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionTerminalSetModeRequest) ProtoMessage() {}

func (x *ProtectionTerminalSetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionTerminalSetModeRequest.ProtoReflect.Descriptor instead.
func (*ProtectionTerminalSetModeRequest) Descriptor() ([]byte, []int) {
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP(), []int{34}
}

func (x *ProtectionTerminalSetModeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtectionTerminalSetModeRequest) GetMode() ProtectionTerminalMode {
	if x != nil {
		return x.Mode
	}
	return ProtectionTerminalMode_MODE_UNKNOWN
}

func (x *ProtectionTerminalSetModeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtectionTerminalSetModeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_api_rtdb_rdss_dms_rtdb_api_proto protoreflect.FileDescriptor

const file_api_rtdb_rdss_dms_rtdb_api_proto_rawDesc = "" +
	"\n" +
	" api/rtdb/rdss_dms_rtdb_api.proto\x12\x10rdss.dms.rtdb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x12\n" +
	"\x10RTDBEmptyRequest\"\x13\n" +
	"\x11RTDBEmptyResponse\"\x8c\x01\n" +
	"\x12RTDBHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12!\n" +
	"\fpoints_count\x18\x03 \x01(\x03R\vpointsCount\"\xba\x01\n" +
	"\rRTDBDataValue\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\rtimestamp_fep\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampFep\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x18\n" +
	"\aquality\x18\x04 \x01(\rR\aquality\"\xd6\x01\n" +
	"\bRTDBItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\tupdate_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.rdss.dms.rtdb.v1.RTDBDataValueR\x04data\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.rdss.dms.rtdb.v1.RTDBItemTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x05 \x01(\x04R\x06source\"\xc1\x01\n" +
	"\x1aRTDBSupervisoryControlItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.rdss.dms.rtdb.v1.RTDBDataValueR\x04data\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x04R\x06source\x12\x16\n" +
	"\x06select\x18\x04 \x01(\bR\x06select\x12\x18\n" +
	"\aexecute\x18\x05 \x01(\bR\aexecute\x12\x12\n" +
	"\x04test\x18\x06 \x01(\bR\x04test\"\xdd\x01\n" +
	"\x1cRTDBSupervisoryControlObject\x12*\n" +
	"\x04mrid\x18\x01 \x01(\v2\x16.rdss.dms.rtdb.v1.UUIDR\x04mrid\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.rdss.dms.rtdb.v1.RTDBDataValueR\x04data\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x04R\x06source\x12\x16\n" +
	"\x06select\x18\x04 \x01(\bR\x06select\x12\x18\n" +
	"\aexecute\x18\x05 \x01(\bR\aexecute\x12\x12\n" +
	"\x04test\x18\x06 \x01(\bR\x04test\"B\n" +
	"\x0fRTDBKeysRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\")\n" +
	"\x15RTDBItemExistsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x16RTDBItemExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x92\x01\n" +
	"\x13RTDBAddItemsRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x04R\x06source\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.rdss.dms.rtdb.v1.RTDBItemTypeR\x04type\"&\n" +
	"\x10RTDBKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"E\n" +
	"\x11RTDBItemsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.rdss.dms.rtdb.v1.RTDBItemR\x05items\"]\n" +
	"\x0eRTDBSourceData\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x04R\x06source\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.rdss.dms.rtdb.v1.RTDBDataValueR\x04data\"_\n" +
	"\x0fRTDBItemSources\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\asources\x18\x02 \x03(\v2 .rdss.dms.rtdb.v1.RTDBSourceDataR\asources\"R\n" +
	"\x17RTDBItemSourcesResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.rdss.dms.rtdb.v1.RTDBItemSourcesR\x05items\"f\n" +
	"\x15RTDBWriteItemsRequest\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.rdss.dms.rtdb.v1.RTDBItemR\x05items\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"~\n" +
	"\x1dRTDBSupervisoryControlRequest\x12@\n" +
	"\x04item\x18\x01 \x01(\v2,.rdss.dms.rtdb.v1.RTDBSupervisoryControlItemR\x04item\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x8a\x01\n" +
	"#RTDBSupervisoryControlObjectRequest\x12F\n" +
	"\x06object\x18\x01 \x01(\v2..rdss.dms.rtdb.v1.RTDBSupervisoryControlObjectR\x06object\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"h\n" +
	"\x1eRTDBSupervisoryControlResponse\x12F\n" +
	"\x06result\x18\x01 \x01(\x0e2..rdss.dms.rtdb.v1.RTDBSupervisoryControlResultR\x06result\"I\n" +
	"\x1fRTDBSetManualEnteredDataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"E\n" +
	"\x15RTDBSetQualityRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x18\n" +
	"\aquality\x18\x02 \x01(\rR\aquality\"p\n" +
	"\rRTDBThreshold\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.rdss.dms.rtdb.v1.RTDBThresholdTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"g\n" +
	"\x1aRTDBDeleteThresholdRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.rdss.dms.rtdb.v1.RTDBThresholdTypeR\x04type\"c\n" +
	"\x12RTDBThresholdValue\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.rdss.dms.rtdb.v1.RTDBThresholdTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"m\n" +
	"\x13RTDBPointThresholds\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\n" +
	"thresholds\x18\x02 \x03(\v2$.rdss.dms.rtdb.v1.RTDBThresholdValueR\n" +
	"thresholds\"U\n" +
	"\x16RTDBThresholdsResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.rdss.dms.rtdb.v1.RTDBPointThresholdsR\x05items\"G\n" +
	"\x1bRTDBSetCurrentSourceRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06source\x18\x02 \x01(\x04R\x06source\"Y\n" +
	"\x19RTDBRegisterSourceRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x04R\x06source\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x03(\tR\x03key\"<\n" +
	"\x0eRTDBSourceInfo\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x04R\x06source\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Q\n" +
	"\x13RTDBSourcesResponse\x12:\n" +
	"\asources\x18\x01 \x03(\v2 .rdss.dms.rtdb.v1.RTDBSourceInfoR\asources\"\xa3\x01\n" +
	"\x14RTDBSubscribeRequest\x12M\n" +
	"\fitem_options\x18\x01 \x03(\v2*.rdss.dms.rtdb.v1.RTDBSubscribeItemOptionsR\vitemOptions\x12\x1f\n" +
	"\vsend_period\x18\x02 \x01(\x05R\n" +
	"sendPeriod\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\x91\x01\n" +
	"\x18RTDBSubscribeItemOptions\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12M\n" +
	"\fcontrol_type\x18\x02 \x01(\x0e2*.rdss.dms.rtdb.v1.RTDBSubscribeDataControlR\vcontrolType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\"\xa7\x01\n" +
	" ProtectionTerminalSetModeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x04mode\x18\x02 \x01(\x0e2(.rdss.dms.rtdb.v1.ProtectionTerminalModeR\x04mode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId*\xcb\x01\n" +
	"\x1cRTDBSupervisoryControlResult\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\rERROR_TIMEOUT\x10\x01\x12\x11\n" +
	"\rERROR_BLOCKED\x10\x02\x12\x10\n" +
	"\fERROR_UNKNOW\x10\x03\x12\x17\n" +
	"\x13ERROR_NOT_SUPPORTED\x10\x04\x12\x1d\n" +
	"\x19ERROR_OBJECT_IS_NOT_FOUND\x10\x05\x12\x1b\n" +
	"\x17ERROR_ITEM_IS_NOT_FOUND\x10\x06\x12\x16\n" +
	"\x12ERROR_NOT_SELECTED\x10\a*\x8f\x01\n" +
	"\x11RTDBThresholdType\x12\x1a\n" +
	"\x16THRESHOLD_TYPE_NOT_SET\x10\x00\x12\x17\n" +
	"\x13UPPER_WARNING_LIMIT\x10\x01\x12\x17\n" +
	"\x13LOWER_WARNING_LIMIT\x10\x02\x12\x15\n" +
	"\x11UPPER_ALARM_LIMIT\x10\x03\x12\x15\n" +
	"\x11LOWER_ALARM_LIMIT\x10\x04*;\n" +
	"\x18RTDBSubscribeDataControl\x12\a\n" +
	"\x03OFF\x10\x00\x12\t\n" +
	"\x05VALUE\x10\x01\x12\v\n" +
	"\aPERCENT\x10\x02*O\n" +
	"\x10RTDBKnownSources\x12\x12\n" +
	"\x0eSOURCE_NOT_SET\x10\x00\x12\x17\n" +
	"\x13MANUAL_ENTERED_DATA\x10\x01\x12\x0e\n" +
	"\n" +
	"CALCULATOR\x10\x02*s\n" +
	"\fRTDBItemType\x12\x10\n" +
	"\fTYPE_NOT_SET\x10\x00\x12\x10\n" +
	"\fDIGITAL_1BIT\x10\x01\x12\x10\n" +
	"\fDIGITAL_2BIT\x10\x02\x12\n" +
	"\n" +
	"\x06ANALOG\x10\x03\x12\x14\n" +
	"\x10PROTECTION_EVENT\x10\x04\x12\v\n" +
	"\aINTEGER\x10\x05*f\n" +
	"\x16ProtectionTerminalMode\x12\x10\n" +
	"\fMODE_UNKNOWN\x10\x00\x12\v\n" +
	"\aMODE_ON\x10\x01\x12\x10\n" +
	"\fMODE_BLOCKED\x10\x02\x12\r\n" +
	"\tMODE_TEST\x10\x03\x12\f\n" +
	"\bMODE_OFF\x10\x052\xc0\x12\n" +
	"\x04Rtdb\x12U\n" +
	"\tGetHealth\x12\".rdss.dms.rtdb.v1.RTDBEmptyRequest\x1a$.rdss.dms.rtdb.v1.RTDBHealthResponse\x12^\n" +
	"\x13ReloadConfiguration\x12\".rdss.dms.rtdb.v1.RTDBEmptyRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12]\n" +
	"\bIsExists\x12'.rdss.dms.rtdb.v1.RTDBItemExistsRequest\x1a(.rdss.dms.rtdb.v1.RTDBItemExistsResponse\x12V\n" +
	"\vGetAllItems\x12\".rdss.dms.rtdb.v1.RTDBEmptyRequest\x1a#.rdss.dms.rtdb.v1.RTDBItemsResponse\x12R\n" +
	"\bGetItems\x12!.rdss.dms.rtdb.v1.RTDBKeysRequest\x1a#.rdss.dms.rtdb.v1.RTDBItemsResponse\x12^\n" +
	"\x0eGetItemSources\x12!.rdss.dms.rtdb.v1.RTDBKeysRequest\x1a).rdss.dms.rtdb.v1.RTDBItemSourcesResponse\x12U\n" +
	"\bAddItems\x12%.rdss.dms.rtdb.v1.RTDBAddItemsRequest\x1a\".rdss.dms.rtdb.v1.RTDBKeysResponse\x12U\n" +
	"\vRemoveItems\x12!.rdss.dms.rtdb.v1.RTDBKeysRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12Y\n" +
	"\tWriteData\x12'.rdss.dms.rtdb.v1.RTDBWriteItemsRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12w\n" +
	"\x12SupervisoryControl\x12/.rdss.dms.rtdb.v1.RTDBSupervisoryControlRequest\x1a0.rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse\x12\x83\x01\n" +
	"\x18SupervisoryControlObject\x125.rdss.dms.rtdb.v1.RTDBSupervisoryControlObjectRequest\x1a0.rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse\x12f\n" +
	"\x10SetCurrentSource\x12-.rdss.dms.rtdb.v1.RTDBSetCurrentSourceRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12b\n" +
	"\x0eRegisterSource\x12+.rdss.dms.rtdb.v1.RTDBRegisterSourceRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12`\n" +
	"\x13GetAvailableSources\x12\".rdss.dms.rtdb.v1.RTDBEmptyRequest\x1a%.rdss.dms.rtdb.v1.RTDBSourcesResponse\x12n\n" +
	"\x14SetManualEnteredData\x121.rdss.dms.rtdb.v1.RTDBSetManualEnteredDataRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12^\n" +
	"\x14GetManualEnteredData\x12!.rdss.dms.rtdb.v1.RTDBKeysRequest\x1a#.rdss.dms.rtdb.v1.RTDBItemsResponse\x12Z\n" +
	"\n" +
	"SetQuality\x12'.rdss.dms.rtdb.v1.RTDBSetQualityRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12\\\n" +
	"\rGetThresholds\x12!.rdss.dms.rtdb.v1.RTDBKeysRequest\x1a(.rdss.dms.rtdb.v1.RTDBThresholdsResponse\x12T\n" +
	"\fAddThreshold\x12\x1f.rdss.dms.rtdb.v1.RTDBThreshold\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12W\n" +
	"\x0fUpdateThreshold\x12\x1f.rdss.dms.rtdb.v1.RTDBThreshold\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12d\n" +
	"\x0fDeleteThreshold\x12,.rdss.dms.rtdb.v1.RTDBDeleteThresholdRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse\x12a\n" +
	"\x0fWriteDataStream\x12'.rdss.dms.rtdb.v1.RTDBWriteItemsRequest\x1a#.rdss.dms.rtdb.v1.RTDBEmptyResponse(\x01\x12Z\n" +
	"\tSubscribe\x12&.rdss.dms.rtdb.v1.RTDBSubscribeRequest\x1a#.rdss.dms.rtdb.v1.RTDBItemsResponse0\x01\x12\x81\x01\n" +
	"\x19ProtectionTerminalSetMode\x122.rdss.dms.rtdb.v1.ProtectionTerminalSetModeRequest\x1a0.rdss.dms.rtdb.v1.RTDBSupervisoryControlResponseB\aZ\x05rtdb/b\x06proto3"

var (
	file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescOnce sync.Once
	file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescData []byte
)

func file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescGZIP() []byte {
	file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescOnce.Do(func() {
		file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rtdb_rdss_dms_rtdb_api_proto_rawDesc), len(file_api_rtdb_rdss_dms_rtdb_api_proto_rawDesc)))
	})
	return file_api_rtdb_rdss_dms_rtdb_api_proto_rawDescData
}

var file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_rtdb_rdss_dms_rtdb_api_proto_goTypes = []any{
	(RTDBSupervisoryControlResult)(0),           // 0: rdss.dms.rtdb.v1.RTDBSupervisoryControlResult
	(RTDBThresholdType)(0),                      // 1: rdss.dms.rtdb.v1.RTDBThresholdType
	(RTDBSubscribeDataControl)(0),               // 2: rdss.dms.rtdb.v1.RTDBSubscribeDataControl
	(RTDBKnownSources)(0),                       // 3: rdss.dms.rtdb.v1.RTDBKnownSources
	(RTDBItemType)(0),                           // 4: rdss.dms.rtdb.v1.RTDBItemType
	(ProtectionTerminalMode)(0),                 // 5: rdss.dms.rtdb.v1.ProtectionTerminalMode
	(*UUID)(nil),                                // 6: rdss.dms.rtdb.v1.UUID
	(*RTDBEmptyRequest)(nil),                    // 7: rdss.dms.rtdb.v1.RTDBEmptyRequest
	(*RTDBEmptyResponse)(nil),                   // 8: rdss.dms.rtdb.v1.RTDBEmptyResponse
	(*RTDBHealthResponse)(nil),                  // 9: rdss.dms.rtdb.v1.RTDBHealthResponse
	(*RTDBDataValue)(nil),                       // 10: rdss.dms.rtdb.v1.RTDBDataValue
	(*RTDBItem)(nil),                            // 11: rdss.dms.rtdb.v1.RTDBItem
	(*RTDBSupervisoryControlItem)(nil),          // 12: rdss.dms.rtdb.v1.RTDBSupervisoryControlItem
	(*RTDBSupervisoryControlObject)(nil),        // 13: rdss.dms.rtdb.v1.RTDBSupervisoryControlObject
	(*RTDBKeysRequest)(nil),                     // 14: rdss.dms.rtdb.v1.RTDBKeysRequest
	(*RTDBItemExistsRequest)(nil),               // 15: rdss.dms.rtdb.v1.RTDBItemExistsRequest
	(*RTDBItemExistsResponse)(nil),              // 16: rdss.dms.rtdb.v1.RTDBItemExistsResponse
	(*RTDBAddItemsRequest)(nil),                 // 17: rdss.dms.rtdb.v1.RTDBAddItemsRequest
	(*RTDBKeysResponse)(nil),                    // 18: rdss.dms.rtdb.v1.RTDBKeysResponse
	(*RTDBItemsResponse)(nil),                   // 19: rdss.dms.rtdb.v1.RTDBItemsResponse
	(*RTDBSourceData)(nil),                      // 20: rdss.dms.rtdb.v1.RTDBSourceData
	(*RTDBItemSources)(nil),                     // 21: rdss.dms.rtdb.v1.RTDBItemSources
	(*RTDBItemSourcesResponse)(nil),             // 22: rdss.dms.rtdb.v1.RTDBItemSourcesResponse
	(*RTDBWriteItemsRequest)(nil),               // 23: rdss.dms.rtdb.v1.RTDBWriteItemsRequest
	(*RTDBSupervisoryControlRequest)(nil),       // 24: rdss.dms.rtdb.v1.RTDBSupervisoryControlRequest
	(*RTDBSupervisoryControlObjectRequest)(nil), // 25: rdss.dms.rtdb.v1.RTDBSupervisoryControlObjectRequest
	(*RTDBSupervisoryControlResponse)(nil),      // 26: rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse
	(*RTDBSetManualEnteredDataRequest)(nil),     // 27: rdss.dms.rtdb.v1.RTDBSetManualEnteredDataRequest
	(*RTDBSetQualityRequest)(nil),               // 28: rdss.dms.rtdb.v1.RTDBSetQualityRequest
	(*RTDBThreshold)(nil),                       // 29: rdss.dms.rtdb.v1.RTDBThreshold
	(*RTDBDeleteThresholdRequest)(nil),          // 30: rdss.dms.rtdb.v1.RTDBDeleteThresholdRequest
	(*RTDBThresholdValue)(nil),                  // 31: rdss.dms.rtdb.v1.RTDBThresholdValue
	(*RTDBPointThresholds)(nil),                 // 32: rdss.dms.rtdb.v1.RTDBPointThresholds
	(*RTDBThresholdsResponse)(nil),              // 33: rdss.dms.rtdb.v1.RTDBThresholdsResponse
	(*RTDBSetCurrentSourceRequest)(nil),         // 34: rdss.dms.rtdb.v1.RTDBSetCurrentSourceRequest
	(*RTDBRegisterSourceRequest)(nil),           // 35: rdss.dms.rtdb.v1.RTDBRegisterSourceRequest
	(*RTDBSourceInfo)(nil),                      // 36: rdss.dms.rtdb.v1.RTDBSourceInfo
	(*RTDBSourcesResponse)(nil),                 // 37: rdss.dms.rtdb.v1.RTDBSourcesResponse
	(*RTDBSubscribeRequest)(nil),                // 38: rdss.dms.rtdb.v1.RTDBSubscribeRequest
	(*RTDBSubscribeItemOptions)(nil),            // 39: rdss.dms.rtdb.v1.RTDBSubscribeItemOptions
	(*ProtectionTerminalSetModeRequest)(nil),    // 40: rdss.dms.rtdb.v1.ProtectionTerminalSetModeRequest
	(*timestamppb.Timestamp)(nil),               // 41: google.protobuf.Timestamp
}
var file_api_rtdb_rdss_dms_rtdb_api_proto_depIdxs = []int32{
	41, // 0: rdss.dms.rtdb.v1.RTDBHealthResponse.start_time:type_name -> google.protobuf.Timestamp
	41, // 1: rdss.dms.rtdb.v1.RTDBDataValue.timestamp:type_name -> google.protobuf.Timestamp
	41, // 2: rdss.dms.rtdb.v1.RTDBDataValue.timestamp_fep:type_name -> google.protobuf.Timestamp
	41, // 3: rdss.dms.rtdb.v1.RTDBItem.update_at:type_name -> google.protobuf.Timestamp
	10, // 4: rdss.dms.rtdb.v1.RTDBItem.data:type_name -> rdss.dms.rtdb.v1.RTDBDataValue
	4,  // 5: rdss.dms.rtdb.v1.RTDBItem.type:type_name -> rdss.dms.rtdb.v1.RTDBItemType
	10, // 6: rdss.dms.rtdb.v1.RTDBSupervisoryControlItem.data:type_name -> rdss.dms.rtdb.v1.RTDBDataValue
	6,  // 7: rdss.dms.rtdb.v1.RTDBSupervisoryControlObject.mrid:type_name -> rdss.dms.rtdb.v1.UUID
	10, // 8: rdss.dms.rtdb.v1.RTDBSupervisoryControlObject.data:type_name -> rdss.dms.rtdb.v1.RTDBDataValue
	4,  // 9: rdss.dms.rtdb.v1.RTDBAddItemsRequest.type:type_name -> rdss.dms.rtdb.v1.RTDBItemType
	11, // 10: rdss.dms.rtdb.v1.RTDBItemsResponse.items:type_name -> rdss.dms.rtdb.v1.RTDBItem
	10, // 11: rdss.dms.rtdb.v1.RTDBSourceData.data:type_name -> rdss.dms.rtdb.v1.RTDBDataValue
	20, // 12: rdss.dms.rtdb.v1.RTDBItemSources.sources:type_name -> rdss.dms.rtdb.v1.RTDBSourceData
	21, // 13: rdss.dms.rtdb.v1.RTDBItemSourcesResponse.items:type_name -> rdss.dms.rtdb.v1.RTDBItemSources
	11, // 14: rdss.dms.rtdb.v1.RTDBWriteItemsRequest.items:type_name -> rdss.dms.rtdb.v1.RTDBItem
	12, // 15: rdss.dms.rtdb.v1.RTDBSupervisoryControlRequest.item:type_name -> rdss.dms.rtdb.v1.RTDBSupervisoryControlItem
	13, // 16: rdss.dms.rtdb.v1.RTDBSupervisoryControlObjectRequest.object:type_name -> rdss.dms.rtdb.v1.RTDBSupervisoryControlObject
	0,  // 17: rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse.result:type_name -> rdss.dms.rtdb.v1.RTDBSupervisoryControlResult
	1,  // 18: rdss.dms.rtdb.v1.RTDBThreshold.type:type_name -> rdss.dms.rtdb.v1.RTDBThresholdType
	1,  // 19: rdss.dms.rtdb.v1.RTDBDeleteThresholdRequest.type:type_name -> rdss.dms.rtdb.v1.RTDBThresholdType
	1,  // 20: rdss.dms.rtdb.v1.RTDBThresholdValue.type:type_name -> rdss.dms.rtdb.v1.RTDBThresholdType
	31, // 21: rdss.dms.rtdb.v1.RTDBPointThresholds.thresholds:type_name -> rdss.dms.rtdb.v1.RTDBThresholdValue
	32, // 22: rdss.dms.rtdb.v1.RTDBThresholdsResponse.items:type_name -> rdss.dms.rtdb.v1.RTDBPointThresholds
	36, // 23: rdss.dms.rtdb.v1.RTDBSourcesResponse.sources:type_name -> rdss.dms.rtdb.v1.RTDBSourceInfo
	39, // 24: rdss.dms.rtdb.v1.RTDBSubscribeRequest.item_options:type_name -> rdss.dms.rtdb.v1.RTDBSubscribeItemOptions
	2,  // 25: rdss.dms.rtdb.v1.RTDBSubscribeItemOptions.control_type:type_name -> rdss.dms.rtdb.v1.RTDBSubscribeDataControl
	5,  // 26: rdss.dms.rtdb.v1.ProtectionTerminalSetModeRequest.mode:type_name -> rdss.dms.rtdb.v1.ProtectionTerminalMode
	7,  // 27: rdss.dms.rtdb.v1.Rtdb.GetHealth:input_type -> rdss.dms.rtdb.v1.RTDBEmptyRequest
	7,  // 28: rdss.dms.rtdb.v1.Rtdb.ReloadConfiguration:input_type -> rdss.dms.rtdb.v1.RTDBEmptyRequest
	15, // 29: rdss.dms.rtdb.v1.Rtdb.IsExists:input_type -> rdss.dms.rtdb.v1.RTDBItemExistsRequest
	7,  // 30: rdss.dms.rtdb.v1.Rtdb.GetAllItems:input_type -> rdss.dms.rtdb.v1.RTDBEmptyRequest
	14, // 31: rdss.dms.rtdb.v1.Rtdb.GetItems:input_type -> rdss.dms.rtdb.v1.RTDBKeysRequest
	14, // 32: rdss.dms.rtdb.v1.Rtdb.GetItemSources:input_type -> rdss.dms.rtdb.v1.RTDBKeysRequest
	17, // 33: rdss.dms.rtdb.v1.Rtdb.AddItems:input_type -> rdss.dms.rtdb.v1.RTDBAddItemsRequest
	14, // 34: rdss.dms.rtdb.v1.Rtdb.RemoveItems:input_type -> rdss.dms.rtdb.v1.RTDBKeysRequest
	23, // 35: rdss.dms.rtdb.v1.Rtdb.WriteData:input_type -> rdss.dms.rtdb.v1.RTDBWriteItemsRequest
	24, // 36: rdss.dms.rtdb.v1.Rtdb.SupervisoryControl:input_type -> rdss.dms.rtdb.v1.RTDBSupervisoryControlRequest
	25, // 37: rdss.dms.rtdb.v1.Rtdb.SupervisoryControlObject:input_type -> rdss.dms.rtdb.v1.RTDBSupervisoryControlObjectRequest
	34, // 38: rdss.dms.rtdb.v1.Rtdb.SetCurrentSource:input_type -> rdss.dms.rtdb.v1.RTDBSetCurrentSourceRequest
	35, // 39: rdss.dms.rtdb.v1.Rtdb.RegisterSource:input_type -> rdss.dms.rtdb.v1.RTDBRegisterSourceRequest
	7,  // 40: rdss.dms.rtdb.v1.Rtdb.GetAvailableSources:input_type -> rdss.dms.rtdb.v1.RTDBEmptyRequest
	27, // 41: rdss.dms.rtdb.v1.Rtdb.SetManualEnteredData:input_type -> rdss.dms.rtdb.v1.RTDBSetManualEnteredDataRequest
	14, // 42: rdss.dms.rtdb.v1.Rtdb.GetManualEnteredData:input_type -> rdss.dms.rtdb.v1.RTDBKeysRequest
	28, // 43: rdss.dms.rtdb.v1.Rtdb.SetQuality:input_type -> rdss.dms.rtdb.v1.RTDBSetQualityRequest
	14, // 44: rdss.dms.rtdb.v1.Rtdb.GetThresholds:input_type -> rdss.dms.rtdb.v1.RTDBKeysRequest
	29, // 45: rdss.dms.rtdb.v1.Rtdb.AddThreshold:input_type -> rdss.dms.rtdb.v1.RTDBThreshold
	29, // 46: rdss.dms.rtdb.v1.Rtdb.UpdateThreshold:input_type -> rdss.dms.rtdb.v1.RTDBThreshold
	30, // 47: rdss.dms.rtdb.v1.Rtdb.DeleteThreshold:input_type -> rdss.dms.rtdb.v1.RTDBDeleteThresholdRequest
	23, // 48: rdss.dms.rtdb.v1.Rtdb.WriteDataStream:input_type -> rdss.dms.rtdb.v1.RTDBWriteItemsRequest
	38, // 49: rdss.dms.rtdb.v1.Rtdb.Subscribe:input_type -> rdss.dms.rtdb.v1.RTDBSubscribeRequest
	40, // 50: rdss.dms.rtdb.v1.Rtdb.ProtectionTerminalSetMode:input_type -> rdss.dms.rtdb.v1.ProtectionTerminalSetModeRequest
	9,  // 51: rdss.dms.rtdb.v1.Rtdb.GetHealth:output_type -> rdss.dms.rtdb.v1.RTDBHealthResponse
	8,  // 52: rdss.dms.rtdb.v1.Rtdb.ReloadConfiguration:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	16, // 53: rdss.dms.rtdb.v1.Rtdb.IsExists:output_type -> rdss.dms.rtdb.v1.RTDBItemExistsResponse
	19, // 54: rdss.dms.rtdb.v1.Rtdb.GetAllItems:output_type -> rdss.dms.rtdb.v1.RTDBItemsResponse
	19, // 55: rdss.dms.rtdb.v1.Rtdb.GetItems:output_type -> rdss.dms.rtdb.v1.RTDBItemsResponse
	22, // 56: rdss.dms.rtdb.v1.Rtdb.GetItemSources:output_type -> rdss.dms.rtdb.v1.RTDBItemSourcesResponse
	18, // 57: rdss.dms.rtdb.v1.Rtdb.AddItems:output_type -> rdss.dms.rtdb.v1.RTDBKeysResponse
	8,  // 58: rdss.dms.rtdb.v1.Rtdb.RemoveItems:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	8,  // 59: rdss.dms.rtdb.v1.Rtdb.WriteData:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	26, // 60: rdss.dms.rtdb.v1.Rtdb.SupervisoryControl:output_type -> rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse
	26, // 61: rdss.dms.rtdb.v1.Rtdb.SupervisoryControlObject:output_type -> rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse
	8,  // 62: rdss.dms.rtdb.v1.Rtdb.SetCurrentSource:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	8,  // 63: rdss.dms.rtdb.v1.Rtdb.RegisterSource:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	37, // 64: rdss.dms.rtdb.v1.Rtdb.GetAvailableSources:output_type -> rdss.dms.rtdb.v1.RTDBSourcesResponse
	8,  // 65: rdss.dms.rtdb.v1.Rtdb.SetManualEnteredData:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	19, // 66: rdss.dms.rtdb.v1.Rtdb.GetManualEnteredData:output_type -> rdss.dms.rtdb.v1.RTDBItemsResponse
	8,  // 67: rdss.dms.rtdb.v1.Rtdb.SetQuality:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	33, // 68: rdss.dms.rtdb.v1.Rtdb.GetThresholds:output_type -> rdss.dms.rtdb.v1.RTDBThresholdsResponse
	8,  // 69: rdss.dms.rtdb.v1.Rtdb.AddThreshold:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	8,  // 70: rdss.dms.rtdb.v1.Rtdb.UpdateThreshold:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	8,  // 71: rdss.dms.rtdb.v1.Rtdb.DeleteThreshold:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	8,  // 72: rdss.dms.rtdb.v1.Rtdb.WriteDataStream:output_type -> rdss.dms.rtdb.v1.RTDBEmptyResponse
	19, // 73: rdss.dms.rtdb.v1.Rtdb.Subscribe:output_type -> rdss.dms.rtdb.v1.RTDBItemsResponse
	26, // 74: rdss.dms.rtdb.v1.Rtdb.ProtectionTerminalSetMode:output_type -> rdss.dms.rtdb.v1.RTDBSupervisoryControlResponse
	51, // [51:75] is the sub-list for method output_type
	27, // [27:51] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_rtdb_rdss_dms_rtdb_api_proto_init() }
func file_api_rtdb_rdss_dms_rtdb_api_proto_init() {
	if File_api_rtdb_rdss_dms_rtdb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rtdb_rdss_dms_rtdb_api_proto_rawDesc), len(file_api_rtdb_rdss_dms_rtdb_api_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rtdb_rdss_dms_rtdb_api_proto_goTypes,
		DependencyIndexes: file_api_rtdb_rdss_dms_rtdb_api_proto_depIdxs,
		EnumInfos:         file_api_rtdb_rdss_dms_rtdb_api_proto_enumTypes,
		MessageInfos:      file_api_rtdb_rdss_dms_rtdb_api_proto_msgTypes,
	}.Build()
	File_api_rtdb_rdss_dms_rtdb_api_proto = out.File
	file_api_rtdb_rdss_dms_rtdb_api_proto_goTypes = nil
	file_api_rtdb_rdss_dms_rtdb_api_proto_depIdxs = nil
}
