// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: api/scada/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryStream_Subscribe_FullMethodName                 = "/rdss.telemetry.v1.TelemetryStream/Subscribe"
	TelemetryStream_SupervisoryControl_FullMethodName        = "/rdss.telemetry.v1.TelemetryStream/SupervisoryControl"
	TelemetryStream_ProtectionTerminalSetMode_FullMethodName = "/rdss.telemetry.v1.TelemetryStream/ProtectionTerminalSetMode"
)

// TelemetryStreamClient is the client API for TelemetryStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryStreamClient interface {
	Subscribe(ctx context.Context, in *SubstationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubstationUpdate], error)
	// Performs Supervisory Control for the specified tag.
	SupervisoryControl(ctx context.Context, in *ScadaSupervisoryControlRequest, opts ...grpc.CallOption) (*ScadaSupervisoryControlResponse, error)
	// Sets a breaker's IEC 61850 Mod-style operating mode (On/Blocked/Test/
	// Off), controlling whether it accepts control commands and whether its
	// protection function drives real physical output.
	ProtectionTerminalSetMode(ctx context.Context, in *ProtectionTerminalSetModeRequest, opts ...grpc.CallOption) (*ProtectionTerminalSetModeResponse, error)
}

type telemetryStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryStreamClient(cc grpc.ClientConnInterface) TelemetryStreamClient {
	return &telemetryStreamClient{cc}
}

func (c *telemetryStreamClient) Subscribe(ctx context.Context, in *SubstationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubstationUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryStream_ServiceDesc.Streams[0], TelemetryStream_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubstationRequest, SubstationUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryStream_SubscribeClient = grpc.ServerStreamingClient[SubstationUpdate]

func (c *telemetryStreamClient) SupervisoryControl(ctx context.Context, in *ScadaSupervisoryControlRequest, opts ...grpc.CallOption) (*ScadaSupervisoryControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScadaSupervisoryControlResponse)
	err := c.cc.Invoke(ctx, TelemetryStream_SupervisoryControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryStreamClient) ProtectionTerminalSetMode(ctx context.Context, in *ProtectionTerminalSetModeRequest, opts ...grpc.CallOption) (*ProtectionTerminalSetModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtectionTerminalSetModeResponse)
	err := c.cc.Invoke(ctx, TelemetryStream_ProtectionTerminalSetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryStreamServer is the server API for TelemetryStream service.
// All implementations must embed UnimplementedTelemetryStreamServer
// for forward compatibility.
type TelemetryStreamServer interface {
	Subscribe(*SubstationRequest, grpc.ServerStreamingServer[SubstationUpdate]) error
	// Performs Supervisory Control for the specified tag.
	SupervisoryControl(context.Context, *ScadaSupervisoryControlRequest) (*ScadaSupervisoryControlResponse, error)
	// Sets a breaker's IEC 61850 Mod-style operating mode (On/Blocked/Test/
	// Off), controlling whether it accepts control commands and whether its
	// protection function drives real physical output.
	ProtectionTerminalSetMode(context.Context, *ProtectionTerminalSetModeRequest) (*ProtectionTerminalSetModeResponse, error)
	mustEmbedUnimplementedTelemetryStreamServer()
}

// UnimplementedTelemetryStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryStreamServer struct{}

func (UnimplementedTelemetryStreamServer) Subscribe(*SubstationRequest, grpc.ServerStreamingServer[SubstationUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTelemetryStreamServer) SupervisoryControl(context.Context, *ScadaSupervisoryControlRequest) (*ScadaSupervisoryControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupervisoryControl not implemented")
}
func (UnimplementedTelemetryStreamServer) ProtectionTerminalSetMode(context.Context, *ProtectionTerminalSetModeRequest) (*ProtectionTerminalSetModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProtectionTerminalSetMode not implemented")
}
func (UnimplementedTelemetryStreamServer) mustEmbedUnimplementedTelemetryStreamServer() {}
func (UnimplementedTelemetryStreamServer) testEmbeddedByValue()                         {}

// UnsafeTelemetryStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryStreamServer will
// result in compilation errors.
type UnsafeTelemetryStreamServer interface {
	mustEmbedUnimplementedTelemetryStreamServer()
}

func RegisterTelemetryStreamServer(s grpc.ServiceRegistrar, srv TelemetryStreamServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryStream_ServiceDesc, srv)
}

func _TelemetryStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubstationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryStreamServer).Subscribe(m, &grpc.GenericServerStream[SubstationRequest, SubstationUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryStream_SubscribeServer = grpc.ServerStreamingServer[SubstationUpdate]

func _TelemetryStream_SupervisoryControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScadaSupervisoryControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryStreamServer).SupervisoryControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryStream_SupervisoryControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryStreamServer).SupervisoryControl(ctx, req.(*ScadaSupervisoryControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryStream_ProtectionTerminalSetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectionTerminalSetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryStreamServer).ProtectionTerminalSetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryStream_ProtectionTerminalSetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryStreamServer).ProtectionTerminalSetMode(ctx, req.(*ProtectionTerminalSetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryStream_ServiceDesc is the grpc.ServiceDesc for TelemetryStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rdss.telemetry.v1.TelemetryStream",
	HandlerType: (*TelemetryStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupervisoryControl",
			Handler:    _TelemetryStream_SupervisoryControl_Handler,
		},
		{
			MethodName: "ProtectionTerminalSetMode",
			Handler:    _TelemetryStream_ProtectionTerminalSetMode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TelemetryStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/scada/telemetry.proto",
}
