// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: api/scada/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPointType int32

const (
	DataPointType_UNKNOWN DataPointType = 0 // Unknown ???
	DataPointType_FLOAT   DataPointType = 1 // Float analog
	DataPointType_INTEGER DataPointType = 2 // 2-bits DI
	DataPointType_BOOLEAN DataPointType = 3 // 1bit DI
)

// Enum value maps for DataPointType.
var (
	DataPointType_name = map[int32]string{
		0: "UNKNOWN",
		1: "FLOAT",
		2: "INTEGER",
		3: "BOOLEAN",
	}
	DataPointType_value = map[string]int32{
		"UNKNOWN": 0,
		"FLOAT":   1,
		"INTEGER": 2,
		"BOOLEAN": 3,
	}
)

func (x DataPointType) Enum() *DataPointType {
	p := new(DataPointType)
	*p = x
	return p
}

func (x DataPointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPointType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scada_telemetry_proto_enumTypes[0].Descriptor()
}

func (DataPointType) Type() protoreflect.EnumType {
	return &file_api_scada_telemetry_proto_enumTypes[0]
}

func (x DataPointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPointType.Descriptor instead.
func (DataPointType) EnumDescriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{0}
}

type DataPointQuality int32

const (
	DataPointQuality_QDS_GOOD         DataPointQuality = 0
	DataPointQuality_QDS_INVALID      DataPointQuality = 1
	DataPointQuality_QDS_QUESTIONABLE DataPointQuality = 2
	DataPointQuality_QDS_SUBSTITUTED  DataPointQuality = 3
	DataPointQuality_QDS_BLOCKED      DataPointQuality = 4
	DataPointQuality_QDS_TEST         DataPointQuality = 5
)

// Enum value maps for DataPointQuality.
var (
	DataPointQuality_name = map[int32]string{
		0: "QDS_GOOD",
		1: "QDS_INVALID",
		2: "QDS_QUESTIONABLE",
		3: "QDS_SUBSTITUTED",
		4: "QDS_BLOCKED",
		5: "QDS_TEST",
	}
	DataPointQuality_value = map[string]int32{
		"QDS_GOOD":         0,
		"QDS_INVALID":      1,
		"QDS_QUESTIONABLE": 2,
		"QDS_SUBSTITUTED":  3,
		"QDS_BLOCKED":      4,
		"QDS_TEST":         5,
	}
)

func (x DataPointQuality) Enum() *DataPointQuality {
	p := new(DataPointQuality)
	*p = x
	return p
}

func (x DataPointQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPointQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scada_telemetry_proto_enumTypes[1].Descriptor()
}

func (DataPointQuality) Type() protoreflect.EnumType {
	return &file_api_scada_telemetry_proto_enumTypes[1]
}

func (x DataPointQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPointQuality.Descriptor instead.
func (DataPointQuality) EnumDescriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{1}
}

type ScadaSupervisoryControlResult int32

const (
	ScadaSupervisoryControlResult_OK                        ScadaSupervisoryControlResult = 0
	ScadaSupervisoryControlResult_ERROR_TIMEOUT             ScadaSupervisoryControlResult = 1
	ScadaSupervisoryControlResult_ERROR_BLOCKED             ScadaSupervisoryControlResult = 2
	ScadaSupervisoryControlResult_ERROR_UNKNOW              ScadaSupervisoryControlResult = 3
	ScadaSupervisoryControlResult_ERROR_NOT_SUPPORTED       ScadaSupervisoryControlResult = 4
	ScadaSupervisoryControlResult_ERROR_OBJECT_IS_NOT_FOUND ScadaSupervisoryControlResult = 5
	ScadaSupervisoryControlResult_ERROR_ITEM_IS_NOT_FOUND   ScadaSupervisoryControlResult = 6
	ScadaSupervisoryControlResult_ERROR_NOT_SELECTED        ScadaSupervisoryControlResult = 7
)

// Enum value maps for ScadaSupervisoryControlResult.
var (
	ScadaSupervisoryControlResult_name = map[int32]string{
		0: "OK",
		1: "ERROR_TIMEOUT",
		2: "ERROR_BLOCKED",
		3: "ERROR_UNKNOW",
		4: "ERROR_NOT_SUPPORTED",
		5: "ERROR_OBJECT_IS_NOT_FOUND",
		6: "ERROR_ITEM_IS_NOT_FOUND",
		7: "ERROR_NOT_SELECTED",
	}
	ScadaSupervisoryControlResult_value = map[string]int32{
		"OK":                        0,
		"ERROR_TIMEOUT":             1,
		"ERROR_BLOCKED":             2,
		"ERROR_UNKNOW":              3,
		"ERROR_NOT_SUPPORTED":       4,
		"ERROR_OBJECT_IS_NOT_FOUND": 5,
		"ERROR_ITEM_IS_NOT_FOUND":   6,
		"ERROR_NOT_SELECTED":        7,
	}
)

func (x ScadaSupervisoryControlResult) Enum() *ScadaSupervisoryControlResult {
	p := new(ScadaSupervisoryControlResult)
	*p = x
	return p
}

func (x ScadaSupervisoryControlResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScadaSupervisoryControlResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scada_telemetry_proto_enumTypes[2].Descriptor()
}

func (ScadaSupervisoryControlResult) Type() protoreflect.EnumType {
	return &file_api_scada_telemetry_proto_enumTypes[2]
}

func (x ScadaSupervisoryControlResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScadaSupervisoryControlResult.Descriptor instead.
func (ScadaSupervisoryControlResult) EnumDescriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{2}
}

// ProtectionTerminalMode mirrors IEC 61850 Edition 1's Mod/Beh enumeration.
// TEST_BLOCKED (4) is deliberately not modelled by this simulator, so
// values skip from TEST (3) straight to OFF (5).
type ProtectionTerminalMode int32

const (
	ProtectionTerminalMode_MODE_UNKNOWN ProtectionTerminalMode = 0
	ProtectionTerminalMode_MODE_ON      ProtectionTerminalMode = 1
	ProtectionTerminalMode_MODE_BLOCKED ProtectionTerminalMode = 2
	ProtectionTerminalMode_MODE_TEST    ProtectionTerminalMode = 3
	ProtectionTerminalMode_MODE_OFF     ProtectionTerminalMode = 5
)

// Enum value maps for ProtectionTerminalMode.
var (
	ProtectionTerminalMode_name = map[int32]string{
		0: "MODE_UNKNOWN",
		1: "MODE_ON",
		2: "MODE_BLOCKED",
		3: "MODE_TEST",
		5: "MODE_OFF",
	}
	ProtectionTerminalMode_value = map[string]int32{
		"MODE_UNKNOWN": 0,
		"MODE_ON":      1,
		"MODE_BLOCKED": 2,
		"MODE_TEST":    3,
		"MODE_OFF":     5,
	}
)

func (x ProtectionTerminalMode) Enum() *ProtectionTerminalMode {
	p := new(ProtectionTerminalMode)
	*p = x
	return p
}

func (x ProtectionTerminalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtectionTerminalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scada_telemetry_proto_enumTypes[3].Descriptor()
}

func (ProtectionTerminalMode) Type() protoreflect.EnumType {
	return &file_api_scada_telemetry_proto_enumTypes[3]
}

func (x ProtectionTerminalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtectionTerminalMode.Descriptor instead.
func (ProtectionTerminalMode) EnumDescriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{3}
}

type SubstationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // client OR substation UUID from the Hierarchy tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubstationRequest) Reset() {
	*x = SubstationRequest{}
	mi := &file_api_scada_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubstationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstationRequest) ProtoMessage() {}

func (x *SubstationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstationRequest.ProtoReflect.Descriptor instead.
func (*SubstationRequest) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *SubstationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ScadaSupervisoryControlResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Result        ScadaSupervisoryControlResult `protobuf:"varint,1,opt,name=result,proto3,enum=rdss.telemetry.v1.ScadaSupervisoryControlResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScadaSupervisoryControlResponse) Reset() {
	*x = ScadaSupervisoryControlResponse{}
	mi := &file_api_scada_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScadaSupervisoryControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaSupervisoryControlResponse) ProtoMessage() {}

func (x *ScadaSupervisoryControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaSupervisoryControlResponse.ProtoReflect.Descriptor instead.
func (*ScadaSupervisoryControlResponse) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ScadaSupervisoryControlResponse) GetResult() ScadaSupervisoryControlResult {
	if x != nil {
		return x.Result
	}
	return ScadaSupervisoryControlResult_OK
}

type DataPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Point type
	Type DataPointType `protobuf:"varint,2,opt,name=type,proto3,enum=rdss.telemetry.v1.DataPointType" json:"type,omitempty"`
	// Point value
	Value float32 `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	// Quality status
	Quality DataPointQuality `protobuf:"varint,4,opt,name=quality,proto3,enum=rdss.telemetry.v1.DataPointQuality" json:"quality,omitempty"`
	// Point timestamp from RTU
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 timestamp with millisecond precision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_api_scada_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *DataPoint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataPoint) GetType() DataPointType {
	if x != nil {
		return x.Type
	}
	return DataPointType_UNKNOWN
}

func (x *DataPoint) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetQuality() DataPointQuality {
	if x != nil {
		return x.Quality
	}
	return DataPointQuality_QDS_GOOD
}

func (x *DataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SubstationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*DataPoint           `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubstationUpdate) Reset() {
	*x = SubstationUpdate{}
	mi := &file_api_scada_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubstationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstationUpdate) ProtoMessage() {}

func (x *SubstationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstationUpdate.ProtoReflect.Descriptor instead.
func (*SubstationUpdate) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *SubstationUpdate) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type ScadaSupervisoryControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Command value
	Value int64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	// Select flag
	Select bool `protobuf:"varint,3,opt,name=select,proto3" json:"select,omitempty"`
	// Execute flag
	Execute bool `protobuf:"varint,4,opt,name=execute,proto3" json:"execute,omitempty"`
	// Test flag
	Test bool `protobuf:"varint,5,opt,name=test,proto3" json:"test,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScadaSupervisoryControlRequest) Reset() {
	*x = ScadaSupervisoryControlRequest{}
	mi := &file_api_scada_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScadaSupervisoryControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaSupervisoryControlRequest) ProtoMessage() {}

func (x *ScadaSupervisoryControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaSupervisoryControlRequest.ProtoReflect.Descriptor instead.
func (*ScadaSupervisoryControlRequest) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *ScadaSupervisoryControlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ScadaSupervisoryControlRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ScadaSupervisoryControlRequest) GetSelect() bool {
	if x != nil {
		return x.Select
	}
	return false
}

func (x *ScadaSupervisoryControlRequest) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

func (x *ScadaSupervisoryControlRequest) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

func (x *ScadaSupervisoryControlRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ProtectionTerminalSetModeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Point identifier, "<breaker-name>.mode"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The mode to set the breaker to
	Mode ProtectionTerminalMode `protobuf:"varint,2,opt,name=mode,proto3,enum=rdss.telemetry.v1.ProtectionTerminalMode" json:"mode,omitempty"`
	// Why the mode is being changed, for logging
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Client text identifier for logging and debugging
	ClientId      string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectionTerminalSetModeRequest) Reset() {
	*x = ProtectionTerminalSetModeRequest{}
	mi := &file_api_scada_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectionTerminalSetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionTerminalSetModeRequest) ProtoMessage() {}

func (x *ProtectionTerminalSetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionTerminalSetModeRequest.ProtoReflect.Descriptor instead.
func (*ProtectionTerminalSetModeRequest) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *ProtectionTerminalSetModeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtectionTerminalSetModeRequest) GetMode() ProtectionTerminalMode {
	if x != nil {
		return x.Mode
	}
	return ProtectionTerminalMode_MODE_UNKNOWN
}

func (x *ProtectionTerminalSetModeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtectionTerminalSetModeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ProtectionTerminalSetModeResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Result        ScadaSupervisoryControlResult `protobuf:"varint,1,opt,name=result,proto3,enum=rdss.telemetry.v1.ScadaSupervisoryControlResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectionTerminalSetModeResponse) Reset() {
	*x = ProtectionTerminalSetModeResponse{}
	mi := &file_api_scada_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectionTerminalSetModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionTerminalSetModeResponse) ProtoMessage() {}

func (x *ProtectionTerminalSetModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionTerminalSetModeResponse.ProtoReflect.Descriptor instead.
func (*ProtectionTerminalSetModeResponse) Descriptor() ([]byte, []int) {
	return file_api_scada_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *ProtectionTerminalSetModeResponse) GetResult() ScadaSupervisoryControlResult {
	if x != nil {
		return x.Result
	}
	return ScadaSupervisoryControlResult_OK
}

var File_api_scada_telemetry_proto protoreflect.FileDescriptor

const file_api_scada_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x19api/scada/telemetry.proto\x12\x11rdss.telemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11SubstationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x1fScadaSupervisoryControlResponse\x12H\n" +
	"\x06result\x18\x01 \x01(\x0e20.rdss.telemetry.v1.ScadaSupervisoryControlResultR\x06result\"\xe2\x01\n" +
	"\tDataPoint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .rdss.telemetry.v1.DataPointTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\x12=\n" +
	"\aquality\x18\x04 \x01(\x0e2#.rdss.telemetry.v1.DataPointQualityR\aquality\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"H\n" +
	"\x10SubstationUpdate\x124\n" +
	"\x06points\x18\x01 \x03(\v2\x1c.rdss.telemetry.v1.DataPointR\x06points\"\xab\x01\n" +
	"\x1eScadaSupervisoryControlRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x16\n" +
	"\x06select\x18\x03 \x01(\bR\x06select\x12\x18\n" +
	"\aexecute\x18\x04 \x01(\bR\aexecute\x12\x12\n" +
	"\x04test\x18\x05 \x01(\bR\x04test\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\"\xa8\x01\n" +
	" ProtectionTerminalSetModeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x04mode\x18\x02 \x01(\x0e2).rdss.telemetry.v1.ProtectionTerminalModeR\x04mode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"m\n" +
	"!ProtectionTerminalSetModeResponse\x12H\n" +
	"\x06result\x18\x01 \x01(\x0e20.rdss.telemetry.v1.ScadaSupervisoryControlResultR\x06result*A\n" +
	"\rDataPointType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05FLOAT\x10\x01\x12\v\n" +
	"\aINTEGER\x10\x02\x12\v\n" +
	"\aBOOLEAN\x10\x03*{\n" +
	"\x10DataPointQuality\x12\f\n" +
	"\bQDS_GOOD\x10\x00\x12\x0f\n" +
	"\vQDS_INVALID\x10\x01\x12\x14\n" +
	"\x10QDS_QUESTIONABLE\x10\x02\x12\x13\n" +
	"\x0fQDS_SUBSTITUTED\x10\x03\x12\x0f\n" +
	"\vQDS_BLOCKED\x10\x04\x12\f\n" +
	"\bQDS_TEST\x10\x05*\xcc\x01\n" +
	"\x1dScadaSupervisoryControlResult\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\rERROR_TIMEOUT\x10\x01\x12\x11\n" +
	"\rERROR_BLOCKED\x10\x02\x12\x10\n" +
	"\fERROR_UNKNOW\x10\x03\x12\x17\n" +
	"\x13ERROR_NOT_SUPPORTED\x10\x04\x12\x1d\n" +
	"\x19ERROR_OBJECT_IS_NOT_FOUND\x10\x05\x12\x1b\n" +
	"\x17ERROR_ITEM_IS_NOT_FOUND\x10\x06\x12\x16\n" +
	"\x12ERROR_NOT_SELECTED\x10\a*f\n" +
	"\x16ProtectionTerminalMode\x12\x10\n" +
	"\fMODE_UNKNOWN\x10\x00\x12\v\n" +
	"\aMODE_ON\x10\x01\x12\x10\n" +
	"\fMODE_BLOCKED\x10\x02\x12\r\n" +
	"\tMODE_TEST\x10\x03\x12\f\n" +
	"\bMODE_OFF\x10\x052\xf1\x02\n" +
	"\x0fTelemetryStream\x12X\n" +
	"\tSubscribe\x12$.rdss.telemetry.v1.SubstationRequest\x1a#.rdss.telemetry.v1.SubstationUpdate0\x01\x12{\n" +
	"\x12SupervisoryControl\x121.rdss.telemetry.v1.ScadaSupervisoryControlRequest\x1a2.rdss.telemetry.v1.ScadaSupervisoryControlResponse\x12\x86\x01\n" +
	"\x19ProtectionTerminalSetMode\x123.rdss.telemetry.v1.ProtectionTerminalSetModeRequest\x1a4.rdss.telemetry.v1.ProtectionTerminalSetModeResponseB\fZ\n" +
	"telemetry/b\x06proto3"

var (
	file_api_scada_telemetry_proto_rawDescOnce sync.Once
	file_api_scada_telemetry_proto_rawDescData []byte
)

func file_api_scada_telemetry_proto_rawDescGZIP() []byte {
	file_api_scada_telemetry_proto_rawDescOnce.Do(func() {
		file_api_scada_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_scada_telemetry_proto_rawDesc), len(file_api_scada_telemetry_proto_rawDesc)))
	})
	return file_api_scada_telemetry_proto_rawDescData
}

var file_api_scada_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_scada_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_scada_telemetry_proto_goTypes = []any{
	(DataPointType)(0),                        // 0: rdss.telemetry.v1.DataPointType
	(DataPointQuality)(0),                     // 1: rdss.telemetry.v1.DataPointQuality
	(ScadaSupervisoryControlResult)(0),        // 2: rdss.telemetry.v1.ScadaSupervisoryControlResult
	(ProtectionTerminalMode)(0),               // 3: rdss.telemetry.v1.ProtectionTerminalMode
	(*SubstationRequest)(nil),                 // 4: rdss.telemetry.v1.SubstationRequest
	(*ScadaSupervisoryControlResponse)(nil),   // 5: rdss.telemetry.v1.ScadaSupervisoryControlResponse
	(*DataPoint)(nil),                         // 6: rdss.telemetry.v1.DataPoint
	(*SubstationUpdate)(nil),                  // 7: rdss.telemetry.v1.SubstationUpdate
	(*ScadaSupervisoryControlRequest)(nil),    // 8: rdss.telemetry.v1.ScadaSupervisoryControlRequest
	(*ProtectionTerminalSetModeRequest)(nil),  // 9: rdss.telemetry.v1.ProtectionTerminalSetModeRequest
	(*ProtectionTerminalSetModeResponse)(nil), // 10: rdss.telemetry.v1.ProtectionTerminalSetModeResponse
	(*timestamppb.Timestamp)(nil),             // 11: google.protobuf.Timestamp
}
var file_api_scada_telemetry_proto_depIdxs = []int32{
	2,  // 0: rdss.telemetry.v1.ScadaSupervisoryControlResponse.result:type_name -> rdss.telemetry.v1.ScadaSupervisoryControlResult
	0,  // 1: rdss.telemetry.v1.DataPoint.type:type_name -> rdss.telemetry.v1.DataPointType
	1,  // 2: rdss.telemetry.v1.DataPoint.quality:type_name -> rdss.telemetry.v1.DataPointQuality
	11, // 3: rdss.telemetry.v1.DataPoint.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 4: rdss.telemetry.v1.SubstationUpdate.points:type_name -> rdss.telemetry.v1.DataPoint
	3,  // 5: rdss.telemetry.v1.ProtectionTerminalSetModeRequest.mode:type_name -> rdss.telemetry.v1.ProtectionTerminalMode
	2,  // 6: rdss.telemetry.v1.ProtectionTerminalSetModeResponse.result:type_name -> rdss.telemetry.v1.ScadaSupervisoryControlResult
	4,  // 7: rdss.telemetry.v1.TelemetryStream.Subscribe:input_type -> rdss.telemetry.v1.SubstationRequest
	8,  // 8: rdss.telemetry.v1.TelemetryStream.SupervisoryControl:input_type -> rdss.telemetry.v1.ScadaSupervisoryControlRequest
	9,  // 9: rdss.telemetry.v1.TelemetryStream.ProtectionTerminalSetMode:input_type -> rdss.telemetry.v1.ProtectionTerminalSetModeRequest
	7,  // 10: rdss.telemetry.v1.TelemetryStream.Subscribe:output_type -> rdss.telemetry.v1.SubstationUpdate
	5,  // 11: rdss.telemetry.v1.TelemetryStream.SupervisoryControl:output_type -> rdss.telemetry.v1.ScadaSupervisoryControlResponse
	10, // 12: rdss.telemetry.v1.TelemetryStream.ProtectionTerminalSetMode:output_type -> rdss.telemetry.v1.ProtectionTerminalSetModeResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_scada_telemetry_proto_init() }
func file_api_scada_telemetry_proto_init() {
	if File_api_scada_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_scada_telemetry_proto_rawDesc), len(file_api_scada_telemetry_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scada_telemetry_proto_goTypes,
		DependencyIndexes: file_api_scada_telemetry_proto_depIdxs,
		EnumInfos:         file_api_scada_telemetry_proto_enumTypes,
		MessageInfos:      file_api_scada_telemetry_proto_msgTypes,
	}.Build()
	File_api_scada_telemetry_proto = out.File
	file_api_scada_telemetry_proto_goTypes = nil
	file_api_scada_telemetry_proto_depIdxs = nil
}
