// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: api/scada/faultsim.proto

package faultsim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaultSimulator_InjectMeasurement_FullMethodName = "/rdss.faultsim.v1.FaultSimulator/InjectMeasurement"
)

// FaultSimulatorClient is the client API for FaultSimulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaultSimulatorClient interface {
	// InjectMeasurement feeds one three-phase measurement into a named
	// breaker, driving its protection evaluation exactly like
	// pkg/breaker.EmulatorFeed.InjectMeasurement — e.g. a current above a
	// breaker's configured instantaneous or time-overcurrent pickup trips it,
	// which in turn may start its autoreclose sequence.
	InjectMeasurement(ctx context.Context, in *InjectMeasurementRequest, opts ...grpc.CallOption) (*InjectMeasurementResponse, error)
}

type faultSimulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultSimulatorClient(cc grpc.ClientConnInterface) FaultSimulatorClient {
	return &faultSimulatorClient{cc}
}

func (c *faultSimulatorClient) InjectMeasurement(ctx context.Context, in *InjectMeasurementRequest, opts ...grpc.CallOption) (*InjectMeasurementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectMeasurementResponse)
	err := c.cc.Invoke(ctx, FaultSimulator_InjectMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaultSimulatorServer is the server API for FaultSimulator service.
// All implementations must embed UnimplementedFaultSimulatorServer
// for forward compatibility.
type FaultSimulatorServer interface {
	// InjectMeasurement feeds one three-phase measurement into a named
	// breaker, driving its protection evaluation exactly like
	// pkg/breaker.EmulatorFeed.InjectMeasurement — e.g. a current above a
	// breaker's configured instantaneous or time-overcurrent pickup trips it,
	// which in turn may start its autoreclose sequence.
	InjectMeasurement(context.Context, *InjectMeasurementRequest) (*InjectMeasurementResponse, error)
	mustEmbedUnimplementedFaultSimulatorServer()
}

// UnimplementedFaultSimulatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaultSimulatorServer struct{}

func (UnimplementedFaultSimulatorServer) InjectMeasurement(context.Context, *InjectMeasurementRequest) (*InjectMeasurementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectMeasurement not implemented")
}
func (UnimplementedFaultSimulatorServer) mustEmbedUnimplementedFaultSimulatorServer() {}
func (UnimplementedFaultSimulatorServer) testEmbeddedByValue()                        {}

// UnsafeFaultSimulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaultSimulatorServer will
// result in compilation errors.
type UnsafeFaultSimulatorServer interface {
	mustEmbedUnimplementedFaultSimulatorServer()
}

func RegisterFaultSimulatorServer(s grpc.ServiceRegistrar, srv FaultSimulatorServer) {
	// If the following call pancis, it indicates UnimplementedFaultSimulatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaultSimulator_ServiceDesc, srv)
}

func _FaultSimulator_InjectMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultSimulatorServer).InjectMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaultSimulator_InjectMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultSimulatorServer).InjectMeasurement(ctx, req.(*InjectMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaultSimulator_ServiceDesc is the grpc.ServiceDesc for FaultSimulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaultSimulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rdss.faultsim.v1.FaultSimulator",
	HandlerType: (*FaultSimulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InjectMeasurement",
			Handler:    _FaultSimulator_InjectMeasurement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scada/faultsim.proto",
}
