// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: api/scada/faultsim.proto

package faultsim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectMeasurementResult int32

const (
	InjectMeasurementResult_OK                      InjectMeasurementResult = 0
	InjectMeasurementResult_ERROR_BREAKER_NOT_FOUND InjectMeasurementResult = 1
)

// Enum value maps for InjectMeasurementResult.
var (
	InjectMeasurementResult_name = map[int32]string{
		0: "OK",
		1: "ERROR_BREAKER_NOT_FOUND",
	}
	InjectMeasurementResult_value = map[string]int32{
		"OK":                      0,
		"ERROR_BREAKER_NOT_FOUND": 1,
	}
)

func (x InjectMeasurementResult) Enum() *InjectMeasurementResult {
	p := new(InjectMeasurementResult)
	*p = x
	return p
}

func (x InjectMeasurementResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InjectMeasurementResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scada_faultsim_proto_enumTypes[0].Descriptor()
}

func (InjectMeasurementResult) Type() protoreflect.EnumType {
	return &file_api_scada_faultsim_proto_enumTypes[0]
}

func (x InjectMeasurementResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InjectMeasurementResult.Descriptor instead.
func (InjectMeasurementResult) EnumDescriptor() ([]byte, []int) {
	return file_api_scada_faultsim_proto_rawDescGZIP(), []int{0}
}

type PhaseValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	C             float64                `protobuf:"fixed64,3,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseValues) Reset() {
	*x = PhaseValues{}
	mi := &file_api_scada_faultsim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseValues) ProtoMessage() {}

func (x *PhaseValues) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_faultsim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseValues.ProtoReflect.Descriptor instead.
func (*PhaseValues) Descriptor() ([]byte, []int) {
	return file_api_scada_faultsim_proto_rawDescGZIP(), []int{0}
}

func (x *PhaseValues) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *PhaseValues) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *PhaseValues) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

type InjectMeasurementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which breaker to feed, i.e. its configured Config.Name (e.g. "feeder-1").
	Breaker string `protobuf:"bytes,1,opt,name=breaker,proto3" json:"breaker,omitempty"`
	// Phase currents, amps RMS.
	Current *PhaseValues `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	// Phase voltages, volts RMS, phase-to-neutral.
	Voltage *PhaseValues `protobuf:"bytes,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	// Three-phase active power, W.
	ActivePower float64 `protobuf:"fixed64,4,opt,name=active_power,json=activePower,proto3" json:"active_power,omitempty"`
	// Three-phase reactive power, VAR.
	ReactivePower float64 `protobuf:"fixed64,5,opt,name=reactive_power,json=reactivePower,proto3" json:"reactive_power,omitempty"`
	// Three-phase apparent power, VA.
	ApparentPower float64 `protobuf:"fixed64,6,opt,name=apparent_power,json=apparentPower,proto3" json:"apparent_power,omitempty"`
	// Power-system frequency, Hz.
	Frequency     float64 `protobuf:"fixed64,7,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectMeasurementRequest) Reset() {
	*x = InjectMeasurementRequest{}
	mi := &file_api_scada_faultsim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectMeasurementRequest) ProtoMessage() {}

func (x *InjectMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_faultsim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectMeasurementRequest.ProtoReflect.Descriptor instead.
func (*InjectMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_api_scada_faultsim_proto_rawDescGZIP(), []int{1}
}

func (x *InjectMeasurementRequest) GetBreaker() string {
	if x != nil {
		return x.Breaker
	}
	return ""
}

func (x *InjectMeasurementRequest) GetCurrent() *PhaseValues {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *InjectMeasurementRequest) GetVoltage() *PhaseValues {
	if x != nil {
		return x.Voltage
	}
	return nil
}

func (x *InjectMeasurementRequest) GetActivePower() float64 {
	if x != nil {
		return x.ActivePower
	}
	return 0
}

func (x *InjectMeasurementRequest) GetReactivePower() float64 {
	if x != nil {
		return x.ReactivePower
	}
	return 0
}

func (x *InjectMeasurementRequest) GetApparentPower() float64 {
	if x != nil {
		return x.ApparentPower
	}
	return 0
}

func (x *InjectMeasurementRequest) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type InjectMeasurementResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        InjectMeasurementResult `protobuf:"varint,1,opt,name=result,proto3,enum=rdss.faultsim.v1.InjectMeasurementResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectMeasurementResponse) Reset() {
	*x = InjectMeasurementResponse{}
	mi := &file_api_scada_faultsim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectMeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectMeasurementResponse) ProtoMessage() {}

func (x *InjectMeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scada_faultsim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectMeasurementResponse.ProtoReflect.Descriptor instead.
func (*InjectMeasurementResponse) Descriptor() ([]byte, []int) {
	return file_api_scada_faultsim_proto_rawDescGZIP(), []int{2}
}

func (x *InjectMeasurementResponse) GetResult() InjectMeasurementResult {
	if x != nil {
		return x.Result
	}
	return InjectMeasurementResult_OK
}

var File_api_scada_faultsim_proto protoreflect.FileDescriptor

const file_api_scada_faultsim_proto_rawDesc = "" +
	"\n" +
	"\x18api/scada/faultsim.proto\x12\x10rdss.faultsim.v1\"7\n" +
	"\vPhaseValues\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\x01R\x01c\"\xb5\x02\n" +
	"\x18InjectMeasurementRequest\x12\x18\n" +
	"\abreaker\x18\x01 \x01(\tR\abreaker\x127\n" +
	"\acurrent\x18\x02 \x01(\v2\x1d.rdss.faultsim.v1.PhaseValuesR\acurrent\x127\n" +
	"\avoltage\x18\x03 \x01(\v2\x1d.rdss.faultsim.v1.PhaseValuesR\avoltage\x12!\n" +
	"\factive_power\x18\x04 \x01(\x01R\vactivePower\x12%\n" +
	"\x0ereactive_power\x18\x05 \x01(\x01R\rreactivePower\x12%\n" +
	"\x0eapparent_power\x18\x06 \x01(\x01R\rapparentPower\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\x01R\tfrequency\"^\n" +
	"\x19InjectMeasurementResponse\x12A\n" +
	"\x06result\x18\x01 \x01(\x0e2).rdss.faultsim.v1.InjectMeasurementResultR\x06result*>\n" +
	"\x17InjectMeasurementResult\x12\x06\n" +
	"\x02OK\x10\x00\x12\x1b\n" +
	"\x17ERROR_BREAKER_NOT_FOUND\x10\x012~\n" +
	"\x0eFaultSimulator\x12l\n" +
	"\x11InjectMeasurement\x12*.rdss.faultsim.v1.InjectMeasurementRequest\x1a+.rdss.faultsim.v1.InjectMeasurementResponseB\vZ\tfaultsim/b\x06proto3"

var (
	file_api_scada_faultsim_proto_rawDescOnce sync.Once
	file_api_scada_faultsim_proto_rawDescData []byte
)

func file_api_scada_faultsim_proto_rawDescGZIP() []byte {
	file_api_scada_faultsim_proto_rawDescOnce.Do(func() {
		file_api_scada_faultsim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_scada_faultsim_proto_rawDesc), len(file_api_scada_faultsim_proto_rawDesc)))
	})
	return file_api_scada_faultsim_proto_rawDescData
}

var file_api_scada_faultsim_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_scada_faultsim_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_scada_faultsim_proto_goTypes = []any{
	(InjectMeasurementResult)(0),      // 0: rdss.faultsim.v1.InjectMeasurementResult
	(*PhaseValues)(nil),               // 1: rdss.faultsim.v1.PhaseValues
	(*InjectMeasurementRequest)(nil),  // 2: rdss.faultsim.v1.InjectMeasurementRequest
	(*InjectMeasurementResponse)(nil), // 3: rdss.faultsim.v1.InjectMeasurementResponse
}
var file_api_scada_faultsim_proto_depIdxs = []int32{
	1, // 0: rdss.faultsim.v1.InjectMeasurementRequest.current:type_name -> rdss.faultsim.v1.PhaseValues
	1, // 1: rdss.faultsim.v1.InjectMeasurementRequest.voltage:type_name -> rdss.faultsim.v1.PhaseValues
	0, // 2: rdss.faultsim.v1.InjectMeasurementResponse.result:type_name -> rdss.faultsim.v1.InjectMeasurementResult
	2, // 3: rdss.faultsim.v1.FaultSimulator.InjectMeasurement:input_type -> rdss.faultsim.v1.InjectMeasurementRequest
	3, // 4: rdss.faultsim.v1.FaultSimulator.InjectMeasurement:output_type -> rdss.faultsim.v1.InjectMeasurementResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_scada_faultsim_proto_init() }
func file_api_scada_faultsim_proto_init() {
	if File_api_scada_faultsim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_scada_faultsim_proto_rawDesc), len(file_api_scada_faultsim_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scada_faultsim_proto_goTypes,
		DependencyIndexes: file_api_scada_faultsim_proto_depIdxs,
		EnumInfos:         file_api_scada_faultsim_proto_enumTypes,
		MessageInfos:      file_api_scada_faultsim_proto_msgTypes,
	}.Build()
	File_api_scada_faultsim_proto = out.File
	file_api_scada_faultsim_proto_goTypes = nil
	file_api_scada_faultsim_proto_depIdxs = nil
}
